# Preprocessing & Feature Engineering Roadmap
## 1. Feature Analysis and Feature Engineering
## 2. Data Preprocessing
## 3. Train-Test Split
## 4. Save Dataset for Training

In [148]:
# 1. Import all necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Text preprocessing
import re
from sklearn.model_selection import train_test_split

# Vectorization methods
from sklearn.feature_extraction.text import TfidfVectorizer
from transformers import BertTokenizer, BertModel
import torch

# For saving processed data
import pickle
import joblib

# Display settings
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)

In [149]:

# 2. Load the dataset
email_df = pd.read_csv('datasets/processed/cleaned_email_dataset.csv')
email_df

,sender,subject,body,label,urls,source_dataset,urls_original
0,young esposito <young@iworld.de>,never agree to be a loser,"buck up, your troubles caused by small dimension will soon be over! become a lover no woman will be able to resist! http://whitedone.com/ come. even as nazi tanks were rolling down the streets, the dreamersphilosopher or a journalist. he was still not sure.i do the same.",1,1,CEAS_08,1
1,mok <iplines1983@icable.ph>,befriend jenna jameson,upgrade your sex and pleasures with these techniques http://www.brightmade.com,1,1,CEAS_08,1
2,daily top 10 <karmandeep-opengevl@universalnet.psi.br>,cnn com daily top 10,"the daily top 10>from cnn.com >top videos and stories as of: aug 1, 2008 3:58 pm edt top 10 videos 1. montauk 'monster' http://www.cnn.com/video/partners/email/index.html?url=/video/us/2008/07/31/moos.montauk.monster.cnn is it a devil dog? is it a turtle? is it the montauk monster? cnn's jeanne moos asks, ""what is this thing?"" 2. racy photos of toddler's mom http://www.cnn.com/video/partners/email/index.html?url=/video/crime/2008/07/31/ng.racy.photos.cnn 3. news of the absurd episode 54 http://www.cnn.com/video/partners/email/index.html?url=/video/podcasts/absurd/site/2008/08/01/nota.episode.54.cnn 4. police beating dispute http://www.cnn.com/video/partners/email/index.html?url=/video/us/2008/07/31/levs.police.video.cnn 5. mom pleads for girl's return http://www.cnn.com/video/partners/email/index.html?url=/video/crime/2008/08/01/hill.boss.reigh.plea.cnn 6. defendant fakes heart attack http://www.cnn.com/video/partners/email/index.html?url=/video/crime/2008/08/01/dnt.fake.heart.attack.mxf.whio 7. killer carried victim's head http://www.cnn.com/video/partners/email/index.html?url=/video/world/2008/07/31/natpkg.can.bus.decapitation.ctv 8. murder confession recanted http://www.cnn.com/video/partners/email/index.html?url=/video/world/2008/08/01/blake.brazil.teen.murder.itn 9. anthrax suspect's home http://www.cnn.com/video/partners/email/index.html?url=/video/us/2008/08/01/von.dr.bruce.ivins.home.cnn 10. hecklers interrupt obama talk http://www.cnn.com/video/partners/email/index.html?url=/video/politics/2008/08/01/sot.fl.obama.protesters.baynews9 top 10 stories 1. suspect in beheading identified http://www.cnn.com/2008/world/americas/08/01/canada.beheading/index.html canadian police say vince weiguang li, 40, of edmonton is charged with second-degree murder in the beheading of a man on a bus. 2. judge taken off last jena 6 cases http://www.cnn.com/2008/crime/08/01/jena6.appeal/index.html 3. people mag gets pitt-jolie pix http://www.cnn.com/2008/showbiz/movies/08/01/brangelina.photos.ap/index.html 4. attack in toronto called racial http://www.cnn.com/2008/world/americas/08/01/canada.attack.ap/index.html 5. ireporters' unusual names http://www.cnn.com/2008/living/08/01/unusual.names.irpt/index.html 6. mother pleads for child's return http://www.cnn.com/2008/crime/08/01/rockefeller.kidnapping/index.html 7. karadzic: i made deal with u.s. http://www.cnn.com/2008/world/europe/08/01/karadzic.trial/index.html 8. suspect arrested in swim killings http://www.cnn.com/2008/crime/08/01/wisconsin.shooting.ap/index.html 9. anthrax suspect apparent suicide http://www.cnn.com/2008/crime/08/01/anthrax.death/index.html 10. mccain: obama criticism 'fair' http://www.cnn.com/2008/politics/08/01/campaign.wrap/index.html cnn, the most trusted name in news> cable news network lp, lllp. <> one cnn center, atlanta, georgia 30303 <> 2008 cable news network lp, lllp. <> a time warner company. <>",1,1,CEAS_08,1
3,gretchen suggs <externalsep1@loanofficertool.com>,specialpricespharmmoreinfo,welcomefastshippingcustomersupport http://7iwfna.blu.livefilestore.com/y1pxdx3kwzhba8xhxv8tdhbjhn7tj4vt91yqg5lb5-_hs9yudwmu5woteqbo-knuliisb2qjjiug_bnfnrnh0yosw/index.html,1,1,CEAS_08,1
4,caroline aragon <dwthaidomainnamesm@thaidomainnames.com>,from caroline aragon,yo wu urs mo ou go rc ebo eform rgi orewo iyv m ww en c mo l cfd ic eym k he uys re,1,0,CEAS_08,0
...,...,...,...,...,...,...,...
99110,scc <gerry.rossi4360@kinki-kids.com>,job just for you,"while we may have high expectations of our associates, we also give them high rewards. imagine being part of a stable organization with a sterling reputation - a place where the sydney car centre is an integral part of all that we do. with our car centre personality, you'll not just succeed - you'll thrive. and, with our strong commitment to promoting from within, you'll definitely enjoy your rise to the top. today the sydney car centre is looking for an industrious regional assistant to fasten the process of the delivery of customer payments to the suppliers. the position offered is a part-time job, and will only require from you to be available for 1-2 hours a day. as a regional assistant, you will be supposed to operate with the payments from those customers, based in your country. you will be expected to accept 2-3 transactions to your bank account every week, make certain calculations about every transaction (you will be precisely instructed about it), & transfer the funds to the suppliers by means of western union/money gram less your fee & the charges of the western union/money gram. you will be continuously communicating with the manager from the head office, who will instruct you & give advice regarding every new payment. the ideal candidate will be industrious, goal-oriented person, with the availability of a personal/business bank account suitable to be used for the company needs. knowledge of english, computer literacy and sociability are appreciated. the company guarantees to pay net 10% fee out of the amount of every payment you dealt with and to provide you with the regular income & flexible schedule. all the related expenses you might have (like the western union/money gram chargers, related expenses on traveling) are covered by the company. the more detailed information is available on our web-site http://vacancy-85953.centrecar.jp/vacancies.php, where you can fill in the on-line application form for this position. we would be glad to welcome you in our team! we are looking forward to hearing from you as soon as possible! yours sincerely, christian mcgraw 0x58, 0x0, 0x02, 0x44374339, 0x3, 0x21, 0x73, 0x25, 0x40, 0x3025, 0x8736 root type interface start pra engine 0x6, 0x02, 0x0027 ewt: 0x5 0x91, 0x962, 0x2, 0x8, 0x58248114, 0x8725, 0x87, 0x04060476, 0x07601018, 0x617, 0x6, 0x7107 0x801, 0x76, 0x122, 0x54, 0x1439, 0x027, 0x8, 0x9, 0x3851, 0x43171840 0x51, 0x63, 0x581, 0x635, 0x8, 0x2657, 0x835 0x08, 0x35, 0x68335649, 0x0, 0x778, 0x336, 0x023, 0x139, 0x838, 0x19, 0x0, 0x35528531, 0x612, 0x73 0x9 0x48392110, 0x10611482, 0x52, 0x47640628, 0x57, 0x59, 0x07188777 0x737, 0x494, 0x0524 0x4, 0x6061, 0x4, 0x2478, 0x41, 0x302, 0x732, 0x9648, 0x77, 0x46364872, 0x032, 0x5512, 0x4 api 86f oxsm nzk mnw dec. function: 0x3, 0x3, 0x5581, 0x20032567, 0x5128, 0x927, 0x82308357, 0x40034348 0x480, 0x07, 0x5354, 0x4661, 0x99468361, 0x4872, 0x9081 jp9m define define api ltin type: 0x31 0x058, 0x3865, 0x337, 0x1383, 0x1, 0x5, 0x3, 0x9, 0x1, 0x74497178, 0x470 rhkm: 0x8, 0x94, 0x05918949, 0x48, 0x72, 0x42141023, 0x7, 0x777 lzky: 0x1828, 0x6, 0x94, 0x4188, 0x348, 0x7, 0x763, 0x5, 0x007, 0x131, 0x02969321, 0x71 0x1812, 0x078, 0x1197, 0x539, 0x38, 0x2, 0x1243, 0x4 0x4474, 0x4, 0x71902151, 0x3, 0x5010, 0x3718, 0x61, 0x5, 0x279 0x89, 0x42, 0x15, 0x462, 0x4333, 0x44, 0x46164674, 0x26, 0x34 yw7, engine, 1wd, source, serv.0x526, 0x8, 0x57, 0x34, 0x4, 0x82, 0x32, 0x42415739, 0x8572, 0x9352, 0x6624, 0x8, 0x48078041 e02: 0x04, 0x05089855, 0x42777318, 0x0576, 0x5, 0x8627, 0x0925 0x63051887, 0x38, 0x0962, 0x42, 0x41343367, 0x11, 0x29817983, 0x92, 0x89, 0x3340, 0x8, 0x9917, 0x492, 0x6426, 0x050 37tg p7a7 bzv update lehn 1mv u6um 0x7449, 0x907, 0x4144, 0x7367, 0x832, 0x88541945, 0x231, 0x73, 0x06221122, 0x7433",1,1,TREC_07,1
99111,sydney car centre <merrill8783@168city.com>,the reply for your request for a job place,"while we may have high expectations of our associates, we also give them high rewards. imagine being part of a stable organization with a sterling reputation - a place where the sydney car centre is an integral part of all that we do. with our car centre personality, you'll not just succeed - you'll thrive. and, with our strong commitment to promoting from within, you'll definitely enjoy your rise to the top. today the sydney car centre is looking for an industrious regional assistant to fasten the process of the delivery of customer payments to the suppliers. the position offered is a part-time job, and will only require from you to be available for 1-2 hours a day. as a regional assistant, you will be supposed to operate with the payments from those customers, based in your country. you will be expected to accept 2-3 transactions to your bank account every week, make certain calculations about every transaction (you will be precisely instructed about it), & transfer the funds to the suppliers by means of western union/money gram less your fee & the charges of the western union/money gram. you will be continuously communicating with the manager from the head office, who will instruct you & give advice regarding every new payment. the ideal candidate will be industrious, goal-oriented person, with the availability of a personal/business bank account suitable to be used for the company needs. knowledge of english, computer literacy and sociability are appreciated. the company guarantees to pay net 10% fee out of the amount of every payment you dealt with and to provide you with the regular income & flexible schedule. all the related expenses you might have (like the western union/money gram chargers, related expenses on traveling) are covered by the company. the more detailed information is available on our web-site http://vacancy-51148191.scc2007.hk/vacancies.php, where you can fill in the on-line application form for this position. we would be glad to welcome you in our team! we are looking forward to hearing from you as soon as possible! yours sincerely, esmeralda bowman 0x783, 0x06, 0x998, 0x19708859, 0x36004780, 0x56976267, 0x11 lde, zsi, j67, i7uu, yqly, 9f9, yqyz, common. 0hqv: 0x906, 0x182, 0x539, 0x8, 0x13, 0x83, 0x4, 0x153, 0x05, 0x077, 0x62, 0x89098925, 0x5 0x3788, 0x7, 0x07, 0x0617, 0x396, 0x32003361, 0x06, 0x3711, 0x6 fo5: 0x129, 0x75681121, 0x4674, 0x21065124, 0x02 h0an: 0x959, 0x9, 0x3125, 0x88774924, 0x35084569, 0x7822, 0x7, 0x3641, 0x545, 0x2, 0x85, 0x1, 0x52397105, 0x14249123 78z: 0x5, 0x41, 0x08958647, 0x45, 0x48902683, 0x1, 0x79, 0x8, 0x7314, 0x15713459 s6rq: 0x991, 0x09052202, 0x5, 0x78500922, 0x3, 0x8, 0x58, 0x0028, 0x1542 interface: 0x127, 0x6, 0x59099635, 0x42, 0x91085012 0x9236, 0x6446, 0x25, 0x761, 0x4361, 0x8, 0x331, 0x4, 0x4, 0x00324695, 0x4, 0x9103, 0x2, 0x8 0x05, 0x47, 0x1, 0x2, 0x72187495, 0x9, 0x7, 0x4, 0x8, 0x92161701, 0x9100, 0x16089079 0x65624327, 0x26301430, 0x890, 0x478, 0x46401146, 0x66693446, 0x87, 0x44 source stack media 0jn. yi8: 0x14, 0x58142734 0x6837, 0x6826, 0x6846, 0x4, 0x447, 0x4, 0x8, 0x432, 0x015, 0x62, 0x4980 i44 qta5: 0x1855, 0x22 0x29577865, 0x52326092, 0x13 0x6, 0x89, 0x42647350, 0x8031, 0x23164080, 0x998 0x58, 0x2, 0x4095, 0x23511530, 0x697, 0x1 0x85, 0x138, 0x531, 0x0, 0x98777144, 0x276, 0x9508, 0x3, 0x2 tmp: 0x27, 0x74263581, 0x8, 0x0631, 0x8121, 0x7, 0x089, 0x3183 interface: 0x7, 0x49800350, 0x15, 0x881, 0x7557, 0x1386, 0x8796, 0x412, 0x0146 rev api0x43, 0x55541377, 0x5077, 0x31, 0x20, 0x261, 0x43920406, 0x56, 0x92 wzi: 0x4, 0x39, 0x08759946, 0x6, 0x3, 0x11 root: 0x7, 0x49393920, 0x29, 0x3387, 0x7, 0x4, 0x2, 0x18, 0x3, 0x76, 0x1957, 0x394, 0x603 create. stack: 0x63788219, 0x136, 0x2097, 0x698, 0x83030685, 0x86, 0x43407518, 0x5, 0x00, 0x0823, 0x9694, 0x58291764, 0x4",1,1,TREC_07,1
99112,philippe grosjean <phgrosjean@sciviews.org>,me again about the horrible documentation of tcltk,"for those who are interested, i just cook a little tcltkhelp() functi > >> i think it would help if the tcl/tk manuals were added to the rgui help >> menu. why google when they are >>> ""alberto monteiro"" wrote: >>> >>>> how on earth can i know what are the arguments of any of the functions of >>>> the tcl/tk package? [...] >>> my impression is that you as supposed to look in tck/tk manuals. >>> for example, googling on >>> >>> tk tck getopenfile >>> >>> pointed to this web page: >>> >>> http://www.tcl.tk/man/tcl8.5/tkcmd/getopenfile.htm >>> >>> hope that helps. >>> >> >> mike prager, noaa, beaufort, nc >>> * opinions expressed are personal and not represented otherwise. >>> * any use of tradenames does not constitute a noaa endorsement. >>> >>> >>> r-help@stat.math.ethz .ch mailing list >>> https://stat.ethz.ch/mailman/listinfo/r-help >>> please do read the posting guide >>> http://www.r-project.org/posting-guide.html >>> and provide commented, minimal, self-contained, reproducible code. >>> >>> > > > r-help@stat.math.ethz .ch mailing list > https://stat.ethz.ch/mailman/listinfo/r-help > please do read the posting guide http://www.r-project.org/posting-guide.html > and provide commented, minimal, self-contained, reproducible code. > r-help@stat.math.ethz .ch mailing list https://stat.ethz.ch/mailman/listinfo/r-help please do read the posting guide http://www.r-project.org/posting-guide.html and provide commented, minimal, self-contained, reproducible code.",0,1,TREC_07,1
99113,bernhard wellhofer <bernhard.wellhoefer@gaia-group.com>,rodbc problem,"hello, as i wrote i call sqlfetch(channel,""t_studie"") and this function generates in the background the concrete query. how can i view/log/... the concrete query? regards, bernhard > > from: duprez cédric [mailto:cedric.duprez@ifn.fr] > sent: friday, july 06, 2007 11:59 am > to: bernhard wellhöfer > cc: r-help@stat.math.ethz .ch > subject: re: [r] rodbc problem > > hello, > > the problem seems to be in the query syntax. > can you show us the query you are trying to perform ? > > regards, > > cedric > > -----message d'origine----- > de : r-help-bounces@stat.math.ethz .ch > [mailto:r-help-bounces@stat.math.ethz.ch] de la part de > bernhard wellhöfer > envoyé : vendredi 6 juillet 2007 11:45 > à : r-help@stat.math.ethz .ch > objet : [r] rodbc problem > > hello, > > i use a rodbc connection to a mysql server on a debian > machine. the call to odbcconnect() seems to be ok, but the > result of the first sqlfetch(channel,""t_studie"") retrieves > this data frame: > > [1] ""[rodbc] error: could not sqlexecdirect"" > [2] ""42000 1064 [mysql][odbc 3.51 > driver][mysqld-5.0.22-debian_1bpo1-log]you have an error in > your sql syntax; check the manual that corresponds to your > mysql server version for the right syntax to use near '\\""t_studi(\\004"" > > please note the funny character at the end of the table name > in the error message. > > the ""test data source"" option on the odbc data source name > configuration panel report success. > > who can help me here? > > regards, > > bernhard > > > > > > > [[alternative html version deleted]] > > > r-help@stat.math.ethz .ch mailing list > https://stat.ethz.ch/mailman/listinfo/r-help > please do read the posting guide > http://www.r-project.org/posting-guide.html > and provide commented, minimal, self-contained, reproducible code. > > > r-help@stat.math.ethz .ch mailing list https://stat.ethz.ch/mailman/listinfo/r-help please do read the posting guide http://www.r-project.org/posting-guide.html and provide commented, minimal, self-contained, reproducible code.",0,1,TREC_07,1
99114,danny <pwcusnt@noblecoffee.com>,i wanted the desk at his own laws of the but my orders and what you re no move on,"well, are implicated. when does not the stage where the be seen in minute began. that terminus with some yeahs ago. even if he thundered, hysterically: ends? but at starving wages before then plunged into high the spirit. mallow smiled to form an even he blew smoke i can prove to the stars that never learn to his shoulders, his sudden conviction any personal malevolent demon. gorov shrugged his the necessary. do in city council or not seem i couldn't he. ponyets winced at all concerned to the directions to ruin, and for korellian and that seat was now confusion with such as much law: out upon an honorable chamberlain of the first, time would be done my way of the. especially no sir, the empire of the fame empty and weapons the mob: psychology was the symbolism. and selling and of the new emperor, was fitted it to be done shouted wienis life? have certainly seems, to be very handy little. we you as though we have to remember him in. there's nothing left the recitation of the heathen is no complete? he was pointed out of that he gasped, thinks he had with an afterthought, and so young, there is that, gives us. it now and in numbers. i knew i mean if i'm here, primarily for no green, to his the tip of trader; last father would remind you speaking again. i first on her hair was publis manlio we're receding and see, me: what else; even the main huge, open and his lordship with all the most part of ulterior motive: that he had soured fallen! of the psychological moment, of their own a trader came to the deepening snow filled the time ponyets felt obliged: to fool which at least, i see i buy not: the hundred and down so in quite to shoot a pattern: in the odds. by mathematics; which that won't ever seen constructed at a symbolic analysis in politics and toppled to be some day, of the fall of that become liable to innocence: pre nuclear power in that; successfully. i wanted the desk at his own laws: of the. but my orders and what you're no, move on their demands the board then went on its bass way to the indiscwiminate first, year, or the last statement. in the nuclear blaster whose helping hand bribe with cohse, he were locates you ought to recognize that, was to go at random distribution. it's not many planets which for a flurry, and in the empire! they'd have had seen trantor. i pass the voice was firm but in the rest in local politics. you're icily (i lack of us). how do so. undoubtedly have believed in the recent successfully for it that he will our duty is for myself. the gold from my deah fellow.",1,0,TREC_07,0

In [150]:
# Drop unnecessary columns
email_df = email_df.drop(columns=['source_dataset', 'urls_original'])

print("Columns after dropping:")
print(email_df.columns.tolist())
print(f"\nDataset shape: {email_df.shape}")
print("\nRemaining columns:")
print(email_df.info())

Columns after dropping:
['sender', 'subject', 'body', 'label', 'urls']

Dataset shape: (99115, 5)

Remaining columns:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99115 entries, 0 to 99114
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   sender   99070 non-null  object
 1   subject  97344 non-null  object
 2   body     99097 non-null  object
 3   label    99115 non-null  int64
 4   urls     99115 non-null  int64
dtypes: int64(2), object(3)
memory usage: 3.8+ MB
None

## 1. Feature Analysis and Feature Engineering

##### Working with sender feature

In [151]:
def extract_sender_components(sender):
    """
    Extract sender_name, sender_email, and sender_domain from sender string
    Format: "Name <email@domain.com>" or "email@domain.com"
    """
    if pd.isna(sender) or sender.strip() == '':
        return pd.Series({'sender_name': None, 'sender_email': None, 'sender_domain': None})

    sender = sender.strip()

    # Pattern: "Name <email@domain.com>"
    pattern = r'(.+?)\s*<(.+?)>'
    match = re.search(pattern, sender)

    if match:
        sender_name = match.group(1).strip()
        sender_email = match.group(2).strip()
    else:
        # No name, just email
        sender_name = None
        sender_email = sender.strip()

    # Remove any remaining < or > from email
    if sender_email:
        sender_email = sender_email.replace('<', '').replace('>', '').strip()

    # Extract domain from email
    if sender_email and '@' in sender_email:
        sender_domain = sender_email.split('@')[-1].strip()
    else:
        sender_domain = None

    return pd.Series({
        'sender_name': sender_name,
        'sender_email': sender_email,
        'sender_domain': sender_domain
    })

# Apply extraction
email_df[['sender_name', 'sender_email', 'sender_domain']] = email_df['sender'].apply(extract_sender_components)

print("\nSender components extracted!")
print("\nSample results:")
print(email_df[['sender', 'sender_name', 'sender_email', 'sender_domain']].head(10))

print("\nMissing values check:")
print(email_df[['sender_name', 'sender_email', 'sender_domain']].isnull().sum())

Sender components extracted!

Sample results:
                                                     sender      sender_name  \
0                          young esposito <young@iworld.de>   young esposito
1                               mok <iplines1983@icable.ph>              mok
2    daily top 10 <karmandeep-opengevl@universalnet.psi.br>     daily top 10
3         gretchen suggs <externalsep1@loanofficertool.com>   gretchen suggs
4  caroline aragon <dwthaidomainnamesm@thaidomainnames.com>  caroline aragon
5           replica watches <jhorton@thebakercompanies.com>  replica watches
6                    daily top 10 <acidirev_1972@tcwpg.com>     daily top 10
7                       <qydlqcws-iacfym@issues.apache.org>             None
8             daily top 10 <orn|dent_1973@musicaedischi.it>     daily top 10
9           ambrosius edwin <370jcmiller@flychautauqua.com>  ambrosius edwin

                              sender_email          sender_domain
0                          young@iworld.de              iworld.de
1                    iplines1983@icable.ph              icable.ph
2  karmandeep-opengevl@universalnet.psi.br    universalnet.psi.br
3         externalsep1@loanofficertool.com    loanofficertool.com
4   dwthaidomainnamesm@thaidomainnames.com    thaidomainnames.com
5            jhorton@thebakercompanies.com  thebakercompanies.com
6                  acidirev_1972@tcwpg.com              tcwpg.com
7        qydlqcws-iacfym@issues.apache.org      issues.apache.org
8           orn|dent_1973@musicaedischi.it       musicaedischi.it
9            370jcmiller@flychautauqua.com      flychautauqua.com

Missing values check:
sender_name      9038
sender_email       45
sender_domain    1288
dtype: int64

#### CREATE SENDER FEATURES

In [152]:
# 1. sender_missing - Binary flag if sender is missing
email_df['sender_missing'] = (email_df['sender'].isna() |
                               (email_df['sender'].str.strip() == '')).astype(int)

# 2. sender_name_length - Length of sender name (0 if no name)
email_df['sender_name_length'] = email_df['sender_name'].fillna('').str.len()

# 3. email_local_length - Length of email before @ symbol
def get_email_local_length(email):
    if pd.isna(email) or email.strip() == '':
        return 0
    if '@' in email:
        return len(email.split('@')[0])
    return 0

email_df['email_local_length'] = email_df['sender_email'].apply(get_email_local_length)

# 4. domain_length - Length of domain name
email_df['domain_length'] = email_df['sender_domain'].fillna('').str.len()

# 5. domain_has_numbers - Binary flag if domain contains digits
email_df['domain_has_numbers'] = email_df['sender_domain'].fillna('').str.contains(r'\d', regex=True).astype(int)

# 6. sender_is_noreply - Binary flag if email starts with noreply
def is_noreply(email):
    if pd.isna(email) or email.strip() == '':
        return 0
    email_lower = email.lower()
    return int(bool(re.match(r'^no[-_]?reply', email_lower)))

email_df['sender_is_noreply'] = email_df['sender_email'].apply(is_noreply)

# 7. consecutive_digit_length - Longest sequence of consecutive digits in email local part
def get_consecutive_digit_length(email):
    if pd.isna(email) or email.strip() == '':
        return 0
    local_part = email.split('@')[0] if '@' in email else email
    digit_sequences = re.findall(r'\d+', local_part)
    if digit_sequences:
        return max(len(seq) for seq in digit_sequences)
    return 0

email_df['consecutive_digit_length'] = email_df['sender_email'].apply(get_consecutive_digit_length)

# 8. special_char_count - Count of special characters in email local part
def count_special_chars(email):
    if pd.isna(email) or email.strip() == '':
        return 0
    local_part = email.split('@')[0] if '@' in email else email
    special_chars = re.findall(r'[^a-zA-Z0-9.]', local_part)
    return len(special_chars)

email_df['special_char_count'] = email_df['sender_email'].apply(count_special_chars)

#### INTRINSIC DOMAIN FEATURES (No lookup needed)

In [153]:
# 9. domain_entropy - Measure of randomness in domain name (higher = more random/suspicious)
import math

def calculate_entropy(text):
    """Calculate Shannon entropy - measures randomness of text"""
    if not text or len(text) == 0:
        return 0
    # Count character frequencies
    freq = {}
    for char in text:
        freq[char] = freq.get(char, 0) + 1
    # Calculate entropy
    entropy = 0
    text_len = len(text)
    for count in freq.values():
        probability = count / text_len
        entropy -= probability * math.log2(probability)
    return entropy

def get_domain_entropy(domain):
    if pd.isna(domain) or domain.strip() == '':
        return 0
    # Remove TLD for entropy calculation (focus on main domain)
    domain_parts = domain.split('.')
    if len(domain_parts) >= 2:
        main_domain = '.'.join(domain_parts[:-1])  # Everything except TLD
    else:
        main_domain = domain
    return calculate_entropy(main_domain.lower())

email_df['domain_entropy'] = email_df['sender_domain'].apply(get_domain_entropy)

# 10. domain_vowel_ratio - Ratio of vowels in domain (random domains have unusual ratios)
def get_vowel_ratio(domain):
    if pd.isna(domain) or domain.strip() == '':
        return 0
    domain_clean = re.sub(r'[^a-zA-Z]', '', domain.lower())  # Keep only letters
    if len(domain_clean) == 0:
        return 0
    vowels = 'aeiou'
    vowel_count = sum(1 for char in domain_clean if char in vowels)
    return vowel_count / len(domain_clean)

email_df['domain_vowel_ratio'] = email_df['sender_domain'].apply(get_vowel_ratio)

# 11. domain_consonant_ratio - Ratio of consonants in domain
def get_consonant_ratio(domain):
    if pd.isna(domain) or domain.strip() == '':
        return 0
    domain_clean = re.sub(r'[^a-zA-Z]', '', domain.lower())  # Keep only letters
    if len(domain_clean) == 0:
        return 0
    consonants = 'bcdfghjklmnpqrstvwxyz'
    consonant_count = sum(1 for char in domain_clean if char in consonants)
    return consonant_count / len(domain_clean)

email_df['domain_consonant_ratio'] = email_df['sender_domain'].apply(get_consonant_ratio)

#### LOOKUP-BASED FEATURES (Requires saving statistics)

In [154]:
# 12. domain_frequency - How many times this domain appears in dataset
domain_freq = email_df['sender_domain'].value_counts().to_dict()
email_df['domain_frequency'] = email_df['sender_domain'].map(domain_freq).fillna(0).astype(int)

# 13. is_rare_domain - Binary flag if domain appears 3 or fewer times
email_df['is_rare_domain'] = (email_df['domain_frequency'] <= 3).astype(int)

# 14. Extract TLD for lookup features
def get_domain_tld(domain):
    if pd.isna(domain) or domain.strip() == '':
        return None
    parts = domain.split('.')
    if len(parts) >= 2:
        return parts[-1].lower()
    return None

email_df['domain_tld'] = email_df['sender_domain'].apply(get_domain_tld)

# 15. tld_frequency - How many times this TLD appears in dataset
tld_freq = email_df['domain_tld'].value_counts().to_dict()
email_df['tld_frequency'] = email_df['domain_tld'].map(tld_freq).fillna(0).astype(int)

# 16. tld_phishing_ratio - Ratio of phishing emails for this TLD
tld_phishing_stats = email_df.groupby('domain_tld')['label'].agg(['sum', 'count'])
tld_phishing_ratio_map = (tld_phishing_stats['sum'] / tld_phishing_stats['count']).to_dict()
email_df['tld_phishing_ratio'] = email_df['domain_tld'].map(tld_phishing_ratio_map).fillna(0.5)  # Default 0.5 for unknown

#### CREATE LOOKUP TABLES FOR INFERENCE

In [155]:
# Lookup table 1: Domain frequency
lookup_domain_frequency = domain_freq

# Lookup table 2: TLD frequency
lookup_tld_frequency = tld_freq

# Lookup table 3: TLD phishing ratio
lookup_tld_phishing_ratio = tld_phishing_ratio_map

print(f"Domain frequency lookup table created: {len(lookup_domain_frequency)} unique domains")
print(f"TLD frequency lookup table created: {len(lookup_tld_frequency)} unique TLDs")
print(f"TLD phishing ratio lookup table created: {len(lookup_tld_phishing_ratio)} unique TLDs")

# Display sample from lookup tables
print("\nSample from lookup tables:")
print("\nTop 10 most common domains:")
print(pd.Series(lookup_domain_frequency).sort_values(ascending=False).head(10))
print("\nTop 10 most common TLDs:")
print(pd.Series(lookup_tld_frequency).sort_values(ascending=False).head(10))
print("\nTLD phishing ratios (sample):")
print(pd.Series(lookup_tld_phishing_ratio).sort_values(ascending=False).head(10))

print("\nAll sender features created!")

# Display results
print("\nFeature summary:")
feature_cols = ['sender_missing', 'sender_name_length', 'email_local_length',
                'domain_length', 'domain_has_numbers', 'sender_is_noreply',
                'consecutive_digit_length', 'special_char_count',
                'domain_entropy', 'domain_vowel_ratio', 'domain_consonant_ratio',
                'domain_frequency', 'is_rare_domain', 'tld_frequency', 'tld_phishing_ratio']

print(email_df[feature_cols].describe())

print("\nSample rows with features:")
display_cols = ['sender', 'sender_missing', 'email_local_length', 'domain_length',
                'consecutive_digit_length', 'special_char_count', 'domain_entropy',
                'domain_frequency', 'is_rare_domain', 'tld_phishing_ratio']
print(email_df[display_cols].head(10))

print(f"\nDataset shape: {email_df.shape}")
print(f"Total sender features created: {len(feature_cols)}")

Domain frequency lookup table created: 36853 unique domains
TLD frequency lookup table created: 217 unique TLDs
TLD phishing ratio lookup table created: 217 unique TLDs

Sample from lookup tables:

Top 10 most common domains:
gmail.com                    5677
samba.org                    3026
yahoo.com                    1361
hotmail.com                  1098
mail.cnn.com                  846
broadcast.shareholder.com     791
spamassassin.taint.org        605
python.org                    527
enron.com                     471
issues.apache.org             446
dtype: int64

Top 10 most common TLDs:
com    51945
org    11664
net     9064
de      3684
uk      2575
edu     2237
ca      2112
it       982
fr       961
au       934
dtype: int64

TLD phishing ratios (sample):
0]         1.0
my         1.0
mailbox    1.0
md         1.0
me         1.0
ml         1.0
mn         1.0
ms         1.0
mu         1.0
mw         1.0
dtype: float64

All sender features created!

Feature summary:
       sender_missing  sender_name_length  email_local_length  domain_length  \
count    99115.000000        99115.000000        99115.000000   99115.000000
mean         0.000454           11.761651            9.909660      12.638743
std          0.021303            5.479698            5.670624       4.791309
min          0.000000            0.000000            0.000000       0.000000
25%          0.000000           10.000000            6.000000       9.000000
50%          0.000000           12.000000            9.000000      12.000000
75%          0.000000           15.000000           13.000000      15.000000
max          1.000000          141.000000           79.000000      57.000000

       domain_has_numbers  sender_is_noreply  consecutive_digit_length  \
count        99115.000000       99115.000000              99115.000000
mean             0.042940           0.001806                  0.342299
std              0.202723           0.042459                  1.120744
min              0.000000           0.000000                  0.000000
25%              0.000000           0.000000                  0.000000
50%              0.000000           0.000000                  0.000000
75%              0.000000           0.000000                  0.000000
max              1.000000           1.000000                 75.000000

       special_char_count  domain_entropy  domain_vowel_ratio  \
count        99115.000000    99115.000000        99115.000000
mean             0.145508        2.600202            0.360267
std              0.527332        0.643025            0.097823
min              0.000000        0.000000            0.000000
25%              0.000000        2.281036            0.307692
50%              0.000000        2.725481            0.375000
75%              0.000000        3.077820            0.416667
max             14.000000        4.601410            1.000000

       domain_consonant_ratio  domain_frequency  is_rare_domain  \
count            99115.000000      99115.000000    99115.000000
mean                 0.626718        506.086778        0.422590
std                  0.114181       1389.913740        0.493974
min                  0.000000          0.000000        0.000000
25%                  0.583333          1.000000        0.000000
50%                  0.625000          7.000000        0.000000
75%                  0.687500        106.000000        1.000000
max                  1.000000       5677.000000        1.000000

       tld_frequency  tld_phishing_ratio
count   99115.000000        99115.000000
mean    29793.130253            0.565202
std     23472.724962            0.177083
min         0.000000            0.000000
25%      3684.000000            0.526873
50%     51945.000000            0.655347
75%     51945.000000            0.655347
max     51945.000000            1.000000

Sample rows with features:
                                                     sender  sender_missing  \
0                          young esposito <young@iworld.de>               0
1                               mok <iplines1983@icable.ph>               0
2    daily top 10 <karmandeep-opengevl@universalnet.psi.br>               0
3         gretchen suggs <externalsep1@loanofficertool.com>               0
4  caroline aragon <dwthaidomainnamesm@thaidomainnames.com>               0
5           replica watches <jhorton@thebakercompanies.com>               0
6                    daily top 10 <acidirev_1972@tcwpg.com>               0
7                       <qydlqcws-iacfym@issues.apache.org>               0
8             daily top 10 <orn|dent_1973@musicaedischi.it>               0
9           ambrosius edwin <370jcmiller@flychautauqua.com>               0

   email_local_length  domain_length  consecutive_digit_length  \
0                   5              9                         0
1                  11              9                         4
2                  19             19                         0
3                  12             19                         1
4                  18             19                         0
5                   7             21                         0
6                  13              9                         4
7                  15             17                         0
8                  13             16                         4
9                  11             17                         3

   special_char_count  domain_entropy  domain_frequency  is_rare_domain  \
0                   0        2.584963                 6               0
1                   0        2.584963                 1               1
2                   1        3.500000                 1               1
3                   0        3.106891                 2               1
4                   0        3.189898                 1               1
5                   0        3.690117                 1               1
6                   1        2.321928                 1               1
7                   1        3.026987               446               0
8                   2        3.026987                 1               1
9                   0        2.968919                 1               1

   tld_phishing_ratio
0            0.526873
1            0.914286
2            0.693262
3            0.655347
4            0.655347
5            0.655347
6            0.655347
7            0.228995
8            0.715886
9            0.655347

Dataset shape: (99115, 24)
Total sender features created: 15

In [156]:
email_df

,sender,subject,body,label,urls,sender_name,sender_email,sender_domain,sender_missing,sender_name_length,email_local_length,domain_length,domain_has_numbers,sender_is_noreply,consecutive_digit_length,special_char_count,domain_entropy,domain_vowel_ratio,domain_consonant_ratio,domain_frequency,is_rare_domain,domain_tld,tld_frequency,tld_phishing_ratio
0,young esposito <young@iworld.de>,never agree to be a loser,"buck up, your troubles caused by small dimension will soon be over! become a lover no woman will be able to resist! http://whitedone.com/ come. even as nazi tanks were rolling down the streets, the dreamersphilosopher or a journalist. he was still not sure.i do the same.",1,1,young esposito,young@iworld.de,iworld.de,0,14,5,9,0,0,0,0,2.584963,0.375000,0.625000,6,0,de,3684,0.526873
1,mok <iplines1983@icable.ph>,befriend jenna jameson,upgrade your sex and pleasures with these techniques http://www.brightmade.com,1,1,mok,iplines1983@icable.ph,icable.ph,0,3,11,9,0,0,4,0,2.584963,0.375000,0.625000,1,1,ph,35,0.914286
2,daily top 10 <karmandeep-opengevl@universalnet.psi.br>,cnn com daily top 10,"the daily top 10>from cnn.com >top videos and stories as of: aug 1, 2008 3:58 pm edt top 10 videos 1. montauk 'monster' http://www.cnn.com/video/partners/email/index.html?url=/video/us/2008/07/31/moos.montauk.monster.cnn is it a devil dog? is it a turtle? is it the montauk monster? cnn's jeanne moos asks, ""what is this thing?"" 2. racy photos of toddler's mom http://www.cnn.com/video/partners/email/index.html?url=/video/crime/2008/07/31/ng.racy.photos.cnn 3. news of the absurd episode 54 http://www.cnn.com/video/partners/email/index.html?url=/video/podcasts/absurd/site/2008/08/01/nota.episode.54.cnn 4. police beating dispute http://www.cnn.com/video/partners/email/index.html?url=/video/us/2008/07/31/levs.police.video.cnn 5. mom pleads for girl's return http://www.cnn.com/video/partners/email/index.html?url=/video/crime/2008/08/01/hill.boss.reigh.plea.cnn 6. defendant fakes heart attack http://www.cnn.com/video/partners/email/index.html?url=/video/crime/2008/08/01/dnt.fake.heart.attack.mxf.whio 7. killer carried victim's head http://www.cnn.com/video/partners/email/index.html?url=/video/world/2008/07/31/natpkg.can.bus.decapitation.ctv 8. murder confession recanted http://www.cnn.com/video/partners/email/index.html?url=/video/world/2008/08/01/blake.brazil.teen.murder.itn 9. anthrax suspect's home http://www.cnn.com/video/partners/email/index.html?url=/video/us/2008/08/01/von.dr.bruce.ivins.home.cnn 10. hecklers interrupt obama talk http://www.cnn.com/video/partners/email/index.html?url=/video/politics/2008/08/01/sot.fl.obama.protesters.baynews9 top 10 stories 1. suspect in beheading identified http://www.cnn.com/2008/world/americas/08/01/canada.beheading/index.html canadian police say vince weiguang li, 40, of edmonton is charged with second-degree murder in the beheading of a man on a bus. 2. judge taken off last jena 6 cases http://www.cnn.com/2008/crime/08/01/jena6.appeal/index.html 3. people mag gets pitt-jolie pix http://www.cnn.com/2008/showbiz/movies/08/01/brangelina.photos.ap/index.html 4. attack in toronto called racial http://www.cnn.com/2008/world/americas/08/01/canada.attack.ap/index.html 5. ireporters' unusual names http://www.cnn.com/2008/living/08/01/unusual.names.irpt/index.html 6. mother pleads for child's return http://www.cnn.com/2008/crime/08/01/rockefeller.kidnapping/index.html 7. karadzic: i made deal with u.s. http://www.cnn.com/2008/world/europe/08/01/karadzic.trial/index.html 8. suspect arrested in swim killings http://www.cnn.com/2008/crime/08/01/wisconsin.shooting.ap/index.html 9. anthrax suspect apparent suicide http://www.cnn.com/2008/crime/08/01/anthrax.death/index.html 10. mccain: obama criticism 'fair' http://www.cnn.com/2008/politics/08/01/campaign.wrap/index.html cnn, the most trusted name in news> cable news network lp, lllp. <> one cnn center, atlanta, georgia 30303 <> 2008 cable news network lp, lllp. <> a time warner company. <>",1,1,daily top 10,karmandeep-opengevl@universalnet.psi.br,universalnet.psi.br,0,12,19,19,0,0,0,1,3.500000,0.352941,0.647059,1,1,br,564,0.693262
3,gretchen suggs <externalsep1@loanofficertool.com>,specialpricespharmmoreinfo,welcomefastshippingcustomersupport http://7iwfna.blu.livefilestore.com/y1pxdx3kwzhba8xhxv8tdhbjhn7tj4vt91yqg5lb5-_hs9yudwmu5woteqbo-knuliisb2qjjiug_bnfnrnh0yosw/index.html,1,1,gretchen suggs,externalsep1@loanofficertool.com,loanofficertool.com,0,14,12,19,0,0,1,0,3.106891,0.444444,0.555556,2,1,com,51945,0.655347
4,caroline aragon <dwthaidomainnamesm@thaidomainnames.com>,from caroline aragon,yo wu urs mo ou go rc ebo eform rgi orewo iyv m ww en c mo l cfd ic eym k he uys re,1,0,caroline aragon,dwthaidomainnamesm@thaidomainnames.com,thaidomainnames.com,0,15,18,19,0,0,0,0,3.189898,0.444444,0.555556,1,1,com,51945,0.655347
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99110,scc <gerry.rossi4360@kinki-kids.com>,job just for you,"while we may have high expectations of our associates, we also give them high rewards. imagine being part of a stable organization with a sterling reputation - a place where the sydney car centre is an integral part of all that we do. with our car centre personality, you'll not just succeed - you'll thrive. and, with our strong commitment to promoting from within, you'll definitely enjoy your rise to the top. today the sydney car centre is looking for an industrious regional assistant to fasten the process of the delivery of customer payments to the suppliers. the position offered is a part-time job, and will only require from you to be available for 1-2 hours a day. as a regional assistant, you will be supposed to operate with the payments from those customers, based in your country. you will be expected to accept 2-3 transactions to your bank account every week, make certain calculations about every transaction (you will be precisely instructed about it), & transfer the funds to the suppliers by means of western union/money gram less your fee & the charges of the western union/money gram. you will be continuously communicating with the manager from the head office, who will instruct you & give advice regarding every new payment. the ideal candidate will be industrious, goal-oriented person, with the availability of a personal/business bank account suitable to be used for the company needs. knowledge of english, computer literacy and sociability are appreciated. the company guarantees to pay net 10% fee out of the amount of every payment you dealt with and to provide you with the regular income & flexible schedule. all the related expenses you might have (like the western union/money gram chargers, related expenses on traveling) are covered by the company. the more detailed information is available on our web-site http://vacancy-85953.centrecar.jp/vacancies.php, where you can fill in the on-line application form for this position. we would be glad to welcome you in our team! we are looking forward to hearing from you as soon as possible! yours sincerely, christian mcgraw 0x58, 0x0, 0x02, 0x44374339, 0x3, 0x21, 0x73, 0x25, 0x40, 0x3025, 0x8736 root type interface start pra engine 0x6, 0x02, 0x0027 ewt: 0x5 0x91, 0x962, 0x2, 0x8, 0x58248114, 0x8725, 0x87, 0x04060476, 0x07601018, 0x617, 0x6, 0x7107 0x801, 0x76, 0x122, 0x54, 0x1439, 0x027, 0x8, 0x9, 0x3851, 0x43171840 0x51, 0x63, 0x581, 0x635, 0x8, 0x2657, 0x835 0x08, 0x35, 0x68335649, 0x0, 0x778, 0x336, 0x023, 0x139, 0x838, 0x19, 0x0, 0x35528531, 0x612, 0x73 0x9 0x48392110, 0x10611482, 0x52, 0x47640628, 0x57, 0x59, 0x07188777 0x737, 0x494, 0x0524 0x4, 0x6061, 0x4, 0x2478, 0x41, 0x302, 0x732, 0x9648, 0x77, 0x46364872, 0x032, 0x5512, 0x4 api 86f oxsm nzk mnw dec. function: 0x3, 0x3, 0x5581, 0x20032567, 0x5128, 0x927, 0x82308357, 0x40034348 0x480, 0x07, 0x5354, 0x4661, 0x99468361, 0x4872, 0x9081 jp9m define define api ltin type: 0x31 0x058, 0x3865, 0x337, 0x1383, 0x1, 0x5, 0x3, 0x9, 0x1, 0x74497178, 0x470 rhkm: 0x8, 0x94, 0x05918949, 0x48, 0x72, 0x42141023, 0x7, 0x777 lzky: 0x1828, 0x6, 0x94, 0x4188, 0x348, 0x7, 0x763, 0x5, 0x007, 0x131, 0x02969321, 0x71 0x1812, 0x078, 0x1197, 0x539, 0x38, 0x2, 0x1243, 0x4 0x4474, 0x4, 0x71902151, 0x3, 0x5010, 0x3718, 0x61, 0x5, 0x279 0x89, 0x42, 0x15, 0x462, 0x4333, 0x44, 0x46164674, 0x26, 0x34 yw7, engine, 1wd, source, serv.0x526, 0x8, 0x57, 0x34, 0x4, 0x82, 0x32, 0x42415739, 0x8572, 0x9352, 0x6624, 0x8, 0x48078041 e02: 0x04, 0x05089855, 0x42777318, 0x0576, 0x5, 0x8627, 0x0925 0x63051887, 0x38, 0x0962, 0x42, 0x41343367, 0x11, 0x29817983, 0x92, 0x89, 0x3340, 0x8, 0x9917, 0x492, 0x6426, 0x050 37tg p7a7 bzv update lehn 1mv u6um 0x7449, 0x907, 0x4144, 0x7367, 0x832, 0x88541945, 0x231, 0x73, 0x06221122, 0x7433",1,1,scc,gerry.rossi4360@kinki-kids.com,kinki-kids.com,0,3,15,14,0,0,4,0,2.370951,0.333333,0.666667,34,0,com,51945,0.655347
99111,sydney car centre <merrill8783@168city.com>,the reply for your request for a job place,"while we may have high expectations of our associates, we also give them high rewards. imagine being part of a stable organization with a sterling reputation - a place where the sydney car centre is an integral part of all that we do. with our car centre personality, you'll not just succeed - you'll thrive. and, with our strong commitment to promoting from within, you'll definitely enjoy your rise to the top. today the sydney car centre is looking for an industrious regional assistant to fasten the process of the delivery of customer payments to the suppliers. the position offered is a part-time job, and will only require from you to be available for 1-2 hours a day. as a regional assistant, you will be supposed to operate with the payments from those customers, based in your country. you will be expected to accept 2-3 transactions to your bank account every week, make certain calculations about every transaction (you will be precisely instructed about it), & transfer the funds to the suppliers by means of western union/money gram less your fee & the charges of the western union/money gram. you will be continuously communicating with the manager from the head office, who will instruct you & give advice regarding every new payment. the ideal candidate will be industrious, goal-oriented person, with the availability of a personal/business bank account suitable to be used for the company needs. knowledge of english, computer literacy and sociability are appreciated. the company guarantees to pay net 10% fee out of the amount of every payment you dealt with and to provide you with the regular income & flexible schedule. all the related expenses you might have (like the western union/money gram chargers, related expenses on traveling) are covered by the company. the more detailed information is available on our web-site http://vacancy-51148191.scc2007.hk/vacancies.php, where you can fill in the on-line application form for this position. we would be glad to welcome you in our team! we are looking forward to hearing from you as soon as possible! yours sincerely, esmeralda bowman 0x783, 0x06, 0x998, 0x19708859, 0x36004780, 0x56976267, 0x11 lde, zsi, j67, i7uu, yqly, 9f9, yqyz, common. 0hqv: 0x906, 0x182, 0x539, 0x8, 0x13, 0x83, 0x4, 0x153, 0x05, 0x077, 0x62, 0x89098925, 0x5 0x3788, 0x7, 0x07, 0x0617, 0x396, 0x32003361, 0x06, 0x3711, 0x6 fo5: 0x129, 0x75681121, 0x4674, 0x21065124, 0x02 h0an: 0x959, 0x9, 0x3125, 0x88774924, 0x35084569, 0x7822, 0x7, 0x3641, 0x545, 0x2, 0x85, 0x1, 0x52397105, 0x14249123 78z: 0x5, 0x41, 0x08958647, 0x45, 0x48902683, 0x1, 0x79, 0x8, 0x7314, 0x15713459 s6rq: 0x991, 0x09052202, 0x5, 0x78500922, 0x3, 0x8, 0x58, 0x0028, 0x1542 interface: 0x127, 0x6, 0x59099635, 0x42, 0x91085012 0x9236, 0x6446, 0x25, 0x761, 0x4361, 0x8, 0x331, 0x4, 0x4, 0x00324695, 0x4, 0x9103, 0x2, 0x8 0x05, 0x47, 0x1, 0x2, 0x72187495, 0x9, 0x7, 0x4, 0x8, 0x92161701, 0x9100, 0x16089079 0x65624327, 0x26301430, 0x890, 0x478, 0x46401146, 0x66693446, 0x87, 0x44 source stack media 0jn. yi8: 0x14, 0x58142734 0x6837, 0x6826, 0x6846, 0x4, 0x447, 0x4, 0x8, 0x432, 0x015, 0x62, 0x4980 i44 qta5: 0x1855, 0x22 0x29577865, 0x52326092, 0x13 0x6, 0x89, 0x42647350, 0x8031, 0x23164080, 0x998 0x58, 0x2, 0x4095, 0x23511530, 0x697, 0x1 0x85, 0x138, 0x531, 0x0, 0x98777144, 0x276, 0x9508, 0x3, 0x2 tmp: 0x27, 0x74263581, 0x8, 0x0631, 0x8121, 0x7, 0x089, 0x3183 interface: 0x7, 0x49800350, 0x15, 0x881, 0x7557, 0x1386, 0x8796, 0x412, 0x0146 rev api0x43, 0x55541377, 0x5077, 0x31, 0x20, 0x261, 0x43920406, 0x56, 0x92 wzi: 0x4, 0x39, 0x08759946, 0x6, 0x3, 0x11 root: 0x7, 0x49393920, 0x29, 0x3387, 0x7, 0x4, 0x2, 0x18, 0x3, 0x76, 0x1957, 0x394, 0x603 create. stack: 0x63788219, 0x136, 0x2097, 0x698, 0x83030685, 0x86, 0x43407518, 0x5, 0x00, 0x0823, 0x9694, 0x58291764, 0x4",1,1,sydney car centre,merrill8783@168city.com,168city.com,0,17,11,11,1,0,4,0,2.807355,0.285714,0.714286,24,0,com,51945,0.655347
99112,philippe grosjean <phgrosjean@sciviews.org>,me again about the horrible documentation of tcltk,"for those who are interested, i just cook a little tcltkhelp() functi > >> i think it would help if the tcl/tk manuals were added to the rgui help >> menu. why google when they are >>> ""alberto monteiro"" wrote: >>> >>>> how on earth can i know what are the arguments of any of the functions of >>>> the tcl/tk package? [...] >>> my impression is that you as supposed to look in tck/tk manuals. >>> for example, googling on >>> >>> tk tck getopenfile >>> >>> pointed to this web page: >>> >>> http://www.tcl.tk/man/tcl8.5/tkcmd/getopenfile.htm >>> >>> hope that helps. >>> >> >> mike prager, noaa, beaufort, nc >>> * opinions expressed are personal and not represented otherwise. >>> * any use of tradenames does not constitute a noaa endorsement. >>> >>> >>> r-help@stat.math.ethz .ch mailing list >>> https://stat.ethz.ch/mailman/listinfo/r-help >>> please do read the posting guide >>> http://www.r-project.org/posting-guide.html >>> and provide commented, minimal, self-contained, reproducible code. >>> >>> > > > r-help@stat.math.ethz .ch mailing list > https://stat.ethz.ch/mailman/listinfo/r-help > please do read the posting guide http://www.r-project.org/posting-guide.html > and provide commented, minimal, self-contained, reproducible code. > r-help@stat.math.ethz .ch mailing list https://stat.ethz.ch/mailman/listinfo/r-help please do read the posting guide http://www.r-project.org/posting-guide.html and provide commented, minimal, self-contained, reproducible code.",0,1,philippe grosjean,phgrosjean@sciviews.org,sciviews.org,0,17,10,12,0,0,0,0,2.500000,0.363636,0.636364,8,0,org,11664,0.228995
99113,bernhard wellhofer <bernhard.wellhoefer@gaia-group.com>,rodbc problem,"hello, as i wrote i call sqlfetch(channel,""t_studie"") and this function generates in the background the concrete query. how can i view/log/... the concrete query? regards, bernhard > > from: duprez cédric [mailto:cedric.duprez@ifn.fr] > sent: friday, july 06, 2007 11:59 am > to: bernhard wellhöfer > cc: r-help@stat.math.ethz .ch > subject: re: [r] rodbc problem > > hello, > > the problem seems to be in the query syntax. > can you show us the query you are trying to perform ? > > regards, > > cedric > > -----message d'origine----- > de : r-help-bounces@stat.math.ethz .ch > [mailto:r-help-bounces@stat.math.ethz.ch] de la part de > bernhard wellhöfer > envoyé : vendredi 6 juillet 2007 11:45 > à : r-help@stat.math.ethz .ch > objet : [r] rodbc problem > > hello, > > i use a rodbc connection to a mysql server on a debian > machine. the call to odbcconnect() seems to be ok, but the > result of the first sqlfetch(channel,""t_studie"") retrieves > this data frame: > > [1] ""[rodbc] error: could not sqlexecdirect"" > [2] ""42000 1064 [mysql][odbc 3.51 > driver][mysqld-5.0.22-debian_1bpo1-log]you have an error in > your sql syntax; check the manual that corresponds to your > mysql server version for the right syntax to use near '\\""t_studi(\\004"" > > please note the funny character at the end of the table name > in the error message. > > the ""test data source"" option on the odbc data source name > configuration panel report success. > > who can help me here? > > regards, > > bernhard > > > > > > > [[alternative html version deleted]] > > > r-help@stat.math.ethz .ch mailing list > https://stat.ethz.ch/mailman/listinfo/r-help > please do read the posting guide > http://www.r-project.org/posting-guide.html > and provide commented, minimal, self-contained, reproducible code. > > > r-help@stat.math.ethz .ch mailing list https://stat.ethz.ch/mailman/listinfo/r-help please do read the posting guide http://www.r-project.org/posting-guide.html and provide commented, minimal, self-contained, reproducible code.",0,1,bernhard wellhofer,bernhard.wellhoefer@gaia-group.com,gaia-group.com,0,18,19,14,0,0,0,0,2.921928,0.500000,0.500000,2,1,com,51945,0.655347
99114,danny <pwcusnt@noblecoffee.com>,i wanted the desk at his own laws of the but my orders and what you re no move on,"well, are implicated. when does not the stage where the be seen in minute began. that terminus with some yeahs ago. even if he thundered, hysterically: ends? but at starving wages before then plunged into high the spirit. mallow smiled to form an even he blew smoke i can prove to the stars that never learn to his shoulders, his sudden conviction any personal malevolent demon. gorov shrugged his the necessary. do in city council or not seem i couldn't he. ponyets winced at all concerned to the directions to ruin, and for korellian and that seat was now confusion with such as much law: out upon an honorable chamberlain of the first, time would be done my way of the. especially no sir, the empire of the fame empty and weapons the mob: psychology was the symbolism. and selling and of the new emperor, was fitted it to be done shouted wienis life? have certainly seems, to be very handy little. we you as though we have to remember him in. there's nothing left the recitation of the heathen is no complete? he was pointed out of that he gasped, thinks he had with an afterthought, and so young, there is that, gives us. it now and in numbers. i knew i mean if i'm here, primarily for no green, to his the tip of trader; last father would remind you speaking again. i first on her hair was publis manlio we're receding and see, me: what else; even the main huge, open and his lordship with all the most part of ulterior motive: that he had soured fallen! of the psychological moment, of their own a trader came to the deepening snow filled the time ponyets felt obliged: to fool which at least, i see i buy not: the hundred and down so in quite to shoot a pattern: in the odds. by mathematics; which that won't ever seen constructed at a symbolic analysis in politics and toppled to be some day, of the fall of that become liable to innocence: pre nuclear power in that; successfully. i wanted the desk at his own laws: of the. but my orders and what you're no, move on their demands the board then went on its bass way to the indiscwiminate first, year, or the last statement. in the nuclear blaster whose helping hand bribe with cohse, he were locates you ought to recognize that, was to go at random distribution. it's not many planets which for a flurry, and in the empire! they'd have had seen trantor. i pass the voice was firm but in the rest in local politics. you're icily (i lack of us). how do so. undoubtedly have believed in the recent successfully for it that he will our duty is for myself. the gold from my deah fellow.",1,0,danny,pwcusnt@noblecoffee.com,noblecoffee.com,0,5,7,15,0,0,0,0,2.663533,0.428571,0.571429,2,1,com,51945,0.655347

# Sender Feature Engineering

## Feature Categories

### 1. Basic Sender Features (Always Computable)
These features can be calculated for any email without external data:

- **`sender_missing`**: Binary flag (0/1) indicating if sender field is empty
  - *Purpose*: Phishing emails sometimes have missing sender info

- **`sender_name_length`**: Character count of sender's display name
  - *Purpose*: Very short or very long names can indicate suspicious emails

- **`email_local_length`**: Length of email address before @ symbol
  - *Purpose*: Phishing often uses long random strings (e.g., "dwthaidomainnamesm@...")

- **`domain_length`**: Length of domain name after @ symbol
  - *Purpose*: Suspicious domains are often unusually long

- **`domain_has_numbers`**: Binary flag if domain contains digits
  - *Purpose*: Legitimate domains rarely have numbers

- **`sender_is_noreply`**: Binary flag if email starts with "noreply"
  - *Purpose*: Phishing often impersonates automated systems

- **`consecutive_digit_length`**: Longest sequence of consecutive digits in email local part
  - *Purpose*: Random number sequences (like "iplines1983") indicate auto-generated phishing emails

- **`special_char_count`**: Count of special characters (_, -, |, etc.) in email local part
  - *Purpose*: Excessive special characters indicate randomly generated emails

### 2. Intrinsic Domain Features (No Lookup Required)
These analyze the domain structure itself and work for new/unseen domains:

- **`domain_entropy`**: Shannon entropy measuring randomness of domain name (0-5 scale)
  - *Purpose*: Random character sequences = high entropy = suspicious
  - *Example*: "google" (low entropy) vs "xk9zm2pq" (high entropy)

- **`domain_vowel_ratio`**: Proportion of vowels in domain (0-1 scale)
  - *Purpose*: Real words have natural vowel patterns; random strings don't
  - *Example*: "amazon" (0.50) vs "bcdfgh" (0.00)

- **`domain_consonant_ratio`**: Proportion of consonants in domain (0-1 scale)
  - *Purpose*: Complement to vowel ratio for detecting unpronounceable domains

### 3. Lookup-Based Features (Requires Training Statistics)
These features use statistics calculated from training data:

- **`domain_frequency`**: Number of times this domain appears in training dataset
  - *Purpose*: Legitimate companies send multiple emails; phishing domains are one-time use
  - *Training*: Count occurrences in dataset
  - *Inference*: Lookup domain in saved map; if not found → frequency = 0 (new/suspicious)

- **`is_rare_domain`**: Binary flag if domain appears ≤ 3 times in training data
  - *Purpose*: Rare domains are more likely to be phishing
  - *Depends on*: domain_frequency

- **`tld_frequency`**: Number of times this TLD (.com, .org, etc.) appears in training dataset
  - *Purpose*: Common TLDs (.com, .org) vs rare TLDs (.tk, .xyz)
  - *Training*: Count TLD occurrences
  - *Inference*: Lookup TLD in saved map; if not found → frequency = 0

- **`tld_phishing_ratio`**: Proportion of emails with this TLD that are phishing (0-1 scale)
  - *Purpose*: Some TLDs are heavily used for phishing
  - *Example*: If .xyz has 80% phishing rate in training → ratio = 0.80
  - *Training*: Calculate (phishing_count / total_count) per TLD
  - *Inference*: Lookup TLD in saved map; if not found → use default 0.5 (unknown = 50% risk)

---

## How Lookup Tables Work

### Training Phase (This Notebook):
1. Calculate statistics from entire dataset
2. Create lookup dictionaries:
   - `lookup_domain_frequency`: {domain → count}
   - `lookup_tld_frequency`: {tld → count}
   - `lookup_tld_phishing_ratio`: {tld → phishing_ratio}
3. Save these dictionaries as pickle/joblib files

### Inference Phase (Future - Real-time Email Processing):
1. Load saved lookup tables
2. For new email:
   - Extract domain (e.g., "gmail.com")
   - Look up in `lookup_domain_frequency`
     - If found: use saved count
     - If NOT found: use 0 (new domain = potentially suspicious)
   - Extract TLD (e.g., "com")
   - Look up in `lookup_tld_frequency` and `lookup_tld_phishing_ratio`
     - If found: use saved values
     - If NOT found: use defaults (0 for frequency, 0.5 for phishing ratio)
3. Calculate all intrinsic features normally (no lookup needed)
4. Combine all features and pass to model

### Key Insight:
- **Intrinsic features** (entropy, vowel ratio, etc.) → Always computable for ANY email
- **Lookup features** (frequency, phishing ratio) → Use training statistics as reference
- **Unseen domains/TLDs** → Treated as suspicious (frequency=0) which helps detect new phishing attempts

---

## Feature Importance for Phishing Detection

**High Impact Features:**
- `tld_phishing_ratio` - Directly indicates TLD risk
- `domain_entropy` - Random domains are highly suspicious
- `consecutive_digit_length` - Long digit sequences indicate auto-generation
- `domain_frequency` - One-time domains are suspicious

**Medium Impact Features:**
- `email_local_length` - Very long local parts are suspicious
- `domain_vowel_ratio` - Unpronounceable domains are suspicious
- `special_char_count` - Excessive special chars indicate randomness

**Supporting Features:**
- `sender_missing`, `sender_is_noreply`, `domain_has_numbers` - Additional signals

## SUBJECT FEATURES

In [157]:
# Handle missing subjects - fill with empty string for processing
email_df['subject'] = email_df['subject'].fillna('')

# 1. subject_length - character count
email_df['subject_length'] = email_df['subject'].str.len()

# 2. subject_word_count - number of words
email_df['subject_word_count'] = email_df['subject'].str.split().str.len().fillna(0).astype(int)

# 3. subject_missing - binary flag if subject is empty
email_df['subject_missing'] = (email_df['subject'].str.strip() == '').astype(int)

# 4. subject_exclamation_count - count of !
email_df['subject_exclamation_count'] = email_df['subject'].str.count('!')

# 5. subject_question_count - count of ?
email_df['subject_question_count'] = email_df['subject'].str.count(r'\?')  # FIXED: escaped the ?

# 6. subject_special_char_ratio - ratio of special characters to total characters
def get_special_char_ratio(text):
    if pd.isna(text) or len(text) == 0:
        return 0
    special_chars = re.findall(r'[^a-zA-Z0-9\s]', text)
    return len(special_chars) / len(text)

email_df['subject_special_char_ratio'] = email_df['subject'].apply(get_special_char_ratio)

# 7. subject_avg_word_length - average characters per word
def get_avg_word_length(text):
    if pd.isna(text) or text.strip() == '':
        return 0
    words = text.split()
    if len(words) == 0:
        return 0
    return sum(len(word) for word in words) / len(words)

email_df['subject_avg_word_length'] = email_df['subject'].apply(get_avg_word_length)

# 8. subject_entropy - Shannon entropy (measure of randomness)
def calculate_entropy(text):
    """Calculate Shannon entropy - measures randomness of text"""
    if not text or len(text) == 0:
        return 0
    # Count character frequencies
    freq = {}
    for char in text.lower():
        if char != ' ':  # Ignore spaces
            freq[char] = freq.get(char, 0) + 1
    # Calculate entropy
    entropy = 0
    text_len = len([c for c in text if c != ' '])
    if text_len == 0:
        return 0
    for count in freq.values():
        probability = count / text_len
        entropy -= probability * math.log2(probability)
    return entropy

email_df['subject_entropy'] = email_df['subject'].apply(calculate_entropy)


# Display results
print("\nSubject Feature Summary:")
subject_features = ['subject_length', 'subject_word_count', 'subject_missing',
                    'subject_exclamation_count', 'subject_question_count',
                    'subject_special_char_ratio', 'subject_avg_word_length', 'subject_entropy']

print(email_df[subject_features].describe())

print("\nSample rows:")
print(email_df[['subject', 'subject_length', 'subject_word_count', 'subject_exclamation_count',
                'subject_entropy']].head(10))

print(f"\nTotal subject features: {len(subject_features)}")

Subject Feature Summary:
       subject_length  subject_word_count  subject_missing  \
count    99115.000000        99115.000000     99115.000000
mean        33.279483            5.846229         0.017868
std         23.794542            4.465475         0.132473
min          0.000000            0.000000         0.000000
25%         20.000000            3.000000         0.000000
50%         29.000000            5.000000         0.000000
75%         42.000000            7.000000         0.000000
max       2574.000000          494.000000         1.000000

       subject_exclamation_count  subject_question_count  \
count                    99115.0                 99115.0
mean                         0.0                     0.0
std                          0.0                     0.0
min                          0.0                     0.0
25%                          0.0                     0.0
50%                          0.0                     0.0
75%                          0.0                     0.0
max                          0.0                     0.0

       subject_special_char_ratio  subject_avg_word_length  subject_entropy
count                     99115.0             99115.000000     99115.000000
mean                          0.0                 5.152037         3.486392
std                           0.0                 2.604569         0.648785
min                           0.0                 0.000000         0.000000
25%                           0.0                 4.000000         3.350209
50%                           0.0                 4.833333         3.625000
75%                           0.0                 5.870833         3.829264
max                           0.0                56.000000         4.873970

Sample rows:
                                                                        subject  \
0                                                     never agree to be a loser
1                                                        befriend jenna jameson
2                                                          cnn com daily top 10
3                                                    specialpricespharmmoreinfo
4                                                          from caroline aragon
5                                                               replica watches
6                                                          cnn com daily top 10
7  uri processing turns uuencoded strings into http uri s which then causes fps
8                                                          cnn com daily top 10
9                                                            debt consolidation

   subject_length  subject_word_count  subject_exclamation_count  \
0              25                   6                          0
1              22                   3                          0
2              20                   5                          0
3              26                   1                          0
4              20                   3                          0
5              15                   2                          0
6              20                   5                          0
7              76                  13                          0
8              20                   5                          0
9              18                   2                          0

   subject_entropy
0         3.108695
1         3.321928
2         3.625000
3         3.584303
4         3.266333
5         3.378783
6         3.625000
7         3.760977
8         3.625000
9         3.337175

Total subject features: 8

## BODY + URL FEATURES

In [158]:
# Comprehensive URL pattern covering ALL common URL formats
url_patterns = [
    r'https?://[^\s<>\"\'\)]+',           # http:// or https://
    r'ftp://[^\s<>\"\'\)]+',              # ftp://
    r'ftps://[^\s<>\"\'\)]+',             # ftps://
    r'sftp://[^\s<>\"\'\)]+',             # sftp://
    r'www\.[^\s<>\"\'\)]+',               # www.
    r'file://[^\s<>\"\'\)]+',             # file://
    r'ssh://[^\s<>\"\'\)]+',              # ssh://
    r'telnet://[^\s<>\"\'\)]+',           # telnet://
    r'git://[^\s<>\"\'\)]+',              # git://
    r'svn://[^\s<>\"\'\)]+',              # svn://
    r'mailto:[^\s<>\"\'\)]+',             # mailto:
    r'news:[^\s<>\"\'\)]+',               # news:
    r'nntp://[^\s<>\"\'\)]+',             # nntp://
    r'irc://[^\s<>\"\'\)]+',              # irc://
    r'webcal://[^\s<>\"\'\)]+',           # webcal://
]

In [159]:
# Handle missing body - fill with empty string for processing
email_df['body'] = email_df['body'].fillna('')

# 1. body_length - character count
email_df['body_length'] = email_df['body'].str.len()

# 2. body_word_count - number of words
email_df['body_word_count'] = email_df['body'].str.split().str.len().fillna(0).astype(int)

# 3. body_to_subject_length_ratio - body length / subject length
def get_body_to_subject_ratio(row):
    if row['subject_length'] == 0:
        return 0 if row['body_length'] == 0 else float('inf')
    return row['body_length'] / row['subject_length']

email_df['body_to_subject_length_ratio'] = email_df.apply(get_body_to_subject_ratio, axis=1)
# Replace infinity with a large number for practical use
email_df['body_to_subject_length_ratio'] = email_df['body_to_subject_length_ratio'].replace(float('inf'), 10000)

# 4. body_url_count - count actual URLs in body
def count_urls(text):
    if pd.isna(text) or text.strip() == '':
        return 0
    # Use the comprehensive url_patterns list
    total_urls = 0
    for pattern in url_patterns:
        urls = re.findall(pattern, text)
        total_urls += len(urls)
    return total_urls

email_df['body_url_count'] = email_df['body'].apply(count_urls)

# 5. body_url_density - URLs per 100 words
def get_url_density(row):
    if row['body_word_count'] == 0:
        return 0
    return (row['body_url_count'] / row['body_word_count']) * 100

email_df['body_url_density'] = email_df.apply(get_url_density, axis=1)

# 6. body_exclamation_count - count of !
email_df['body_exclamation_count'] = email_df['body'].str.count('!')

# 7. body_exclamation_density - ! per 100 characters
def get_exclamation_density(row):
    if row['body_length'] == 0:
        return 0
    return (row['body_exclamation_count'] / row['body_length']) * 100

email_df['body_exclamation_density'] = email_df.apply(get_exclamation_density, axis=1)

# 8. body_question_count - count of ?
email_df['body_question_count'] = email_df['body'].str.count(r'\?')  # FIXED: escaped the ?

# 9. body_avg_word_length - average characters per word
email_df['body_avg_word_length'] = email_df['body'].apply(get_avg_word_length)

# 10. body_entropy - Shannon entropy
email_df['body_entropy'] = email_df['body'].apply(calculate_entropy)

# 11. body_unique_word_ratio - unique words / total words
def get_unique_word_ratio(text):
    if pd.isna(text) or text.strip() == '':
        return 0
    words = text.lower().split()
    if len(words) == 0:
        return 0
    unique_words = len(set(words))
    return unique_words / len(words)

email_df['body_unique_word_ratio'] = email_df['body'].apply(get_unique_word_ratio)

# 12. body_line_count - number of lines (newlines)
email_df['body_line_count'] = email_df['body'].str.count('\n') + 1


# Display results
print("\nBody Feature Summary:")
body_features = ['body_length', 'body_word_count', 'body_to_subject_length_ratio',
                 'body_url_count', 'body_url_density', 'body_exclamation_count',
                 'body_exclamation_density', 'body_question_count', 'body_avg_word_length',
                 'body_entropy', 'body_unique_word_ratio', 'body_line_count']

print(email_df[body_features].describe())

print("\nSample rows:")
print(email_df[['body_length', 'body_word_count', 'body_url_count', 'body_url_density',
                'body_exclamation_count', 'body_entropy', 'body_unique_word_ratio']].head(10))

print(f"\nTotal body features: {len(body_features)}")

# Verify URL feature consistency
print("\nURL Feature Verification:")
print(f"Existing 'urls' column (boolean): {email_df['urls'].sum()} emails with URLs")
print(f"New 'body_url_count': {(email_df['body_url_count'] > 0).sum()} emails with URLs")
print(f"Match rate: {((email_df['urls'] == (email_df['body_url_count'] > 0)).sum() / len(email_df)) * 100:.2f}%")

Body Feature Summary:
        body_length  body_word_count  body_to_subject_length_ratio  \
count  99115.000000     99115.000000                  99115.000000
mean    1049.796701       158.891046                    223.591287
std      976.905863       148.747852                   1320.264873
min        0.000000         0.000000                      0.000000
25%      314.000000        51.000000                     10.562500
50%      692.000000       108.000000                     23.428571
75%     1498.000000       224.000000                     57.330460
max     4712.000000       878.000000                  10000.000000

       body_url_count  body_url_density  body_exclamation_count  \
count    99115.000000      99115.000000            99115.000000
mean         2.648136          2.738434                0.814286
std          7.060145          6.316218                1.733625
min          0.000000          0.000000                0.000000
25%          0.000000          0.000000                0.000000
50%          1.000000          0.719424                0.000000
75%          2.000000          2.577320                1.000000
max        128.000000        200.000000               65.000000

       body_exclamation_density  body_question_count  body_avg_word_length  \
count              99115.000000         99115.000000          99115.000000
mean                   0.137344             1.190415              7.222194
std                    0.320708             2.465999             55.565990
min                    0.000000             0.000000              0.000000
25%                    0.000000             0.000000              4.736735
50%                    0.000000             0.000000              5.303797
75%                    0.122100             1.000000              6.136000
max                    7.650273            66.000000           4602.000000

       body_entropy  body_unique_word_ratio  body_line_count
count  99115.000000            99115.000000          99115.0
mean       4.536529                0.755284              1.0
std        0.252442                0.149451              0.0
min        0.000000                0.000000              1.0
25%        4.370643                0.649737              1.0
50%        4.510036                0.764706              1.0
75%        4.696688                0.867647              1.0
max        6.874694                1.000000              1.0

Sample rows:
   body_length  body_word_count  body_url_count  body_url_density  \
0          271               46               1          2.173913
1           78                9               2         22.222222
2         2915              227              40         17.621145
3          171                2               1         50.000000
4           83               25               0          0.000000
5          114               19               0          0.000000
6         2915              227              40         17.621145
7          150               11               1          9.090909
8         2915              227              40         17.621145
9          482               76               2          2.631579

   body_exclamation_count  body_entropy  body_unique_word_ratio
0                       2      4.302561                0.891304
1                       0      4.307525                1.000000
2                       0      4.759651                0.735683
3                       0      5.039773                1.000000
4                       0      3.881709                0.960000
5                       0      4.072783                1.000000
6                       0      4.759651                0.735683
7                       0      4.763243                1.000000
8                       0      4.759651                0.735683
9                       1      4.394576                0.710526

Total body features: 12

URL Feature Verification:
Existing 'urls' column (boolean): 78148 emails with URLs
New 'body_url_count': 57514 emails with URLs
Match rate: 79.18%

In [160]:
email_df

,sender,subject,body,label,urls,sender_name,sender_email,sender_domain,sender_missing,sender_name_length,email_local_length,domain_length,domain_has_numbers,sender_is_noreply,consecutive_digit_length,special_char_count,domain_entropy,domain_vowel_ratio,domain_consonant_ratio,domain_frequency,is_rare_domain,domain_tld,tld_frequency,tld_phishing_ratio,subject_length,subject_word_count,subject_missing,subject_exclamation_count,subject_question_count,subject_special_char_ratio,subject_avg_word_length,subject_entropy,body_length,body_word_count,body_to_subject_length_ratio,body_url_count,body_url_density,body_exclamation_count,body_exclamation_density,body_question_count,body_avg_word_length,body_entropy,body_unique_word_ratio,body_line_count
0,young esposito <young@iworld.de>,never agree to be a loser,"buck up, your troubles caused by small dimension will soon be over! become a lover no woman will be able to resist! http://whitedone.com/ come. even as nazi tanks were rolling down the streets, the dreamersphilosopher or a journalist. he was still not sure.i do the same.",1,1,young esposito,young@iworld.de,iworld.de,0,14,5,9,0,0,0,0,2.584963,0.375000,0.625000,6,0,de,3684,0.526873,25,6,0,0,0,0.0,3.333333,3.108695,271,46,10.840000,1,2.173913,2,0.738007,0,4.913043,4.302561,0.891304,1
1,mok <iplines1983@icable.ph>,befriend jenna jameson,upgrade your sex and pleasures with these techniques http://www.brightmade.com,1,1,mok,iplines1983@icable.ph,icable.ph,0,3,11,9,0,0,4,0,2.584963,0.375000,0.625000,1,1,ph,35,0.914286,22,3,0,0,0,0.0,6.666667,3.321928,78,9,3.545455,2,22.222222,0,0.000000,0,7.777778,4.307525,1.000000,1
2,daily top 10 <karmandeep-opengevl@universalnet.psi.br>,cnn com daily top 10,"the daily top 10>from cnn.com >top videos and stories as of: aug 1, 2008 3:58 pm edt top 10 videos 1. montauk 'monster' http://www.cnn.com/video/partners/email/index.html?url=/video/us/2008/07/31/moos.montauk.monster.cnn is it a devil dog? is it a turtle? is it the montauk monster? cnn's jeanne moos asks, ""what is this thing?"" 2. racy photos of toddler's mom http://www.cnn.com/video/partners/email/index.html?url=/video/crime/2008/07/31/ng.racy.photos.cnn 3. news of the absurd episode 54 http://www.cnn.com/video/partners/email/index.html?url=/video/podcasts/absurd/site/2008/08/01/nota.episode.54.cnn 4. police beating dispute http://www.cnn.com/video/partners/email/index.html?url=/video/us/2008/07/31/levs.police.video.cnn 5. mom pleads for girl's return http://www.cnn.com/video/partners/email/index.html?url=/video/crime/2008/08/01/hill.boss.reigh.plea.cnn 6. defendant fakes heart attack http://www.cnn.com/video/partners/email/index.html?url=/video/crime/2008/08/01/dnt.fake.heart.attack.mxf.whio 7. killer carried victim's head http://www.cnn.com/video/partners/email/index.html?url=/video/world/2008/07/31/natpkg.can.bus.decapitation.ctv 8. murder confession recanted http://www.cnn.com/video/partners/email/index.html?url=/video/world/2008/08/01/blake.brazil.teen.murder.itn 9. anthrax suspect's home http://www.cnn.com/video/partners/email/index.html?url=/video/us/2008/08/01/von.dr.bruce.ivins.home.cnn 10. hecklers interrupt obama talk http://www.cnn.com/video/partners/email/index.html?url=/video/politics/2008/08/01/sot.fl.obama.protesters.baynews9 top 10 stories 1. suspect in beheading identified http://www.cnn.com/2008/world/americas/08/01/canada.beheading/index.html canadian police say vince weiguang li, 40, of edmonton is charged with second-degree murder in the beheading of a man on a bus. 2. judge taken off last jena 6 cases http://www.cnn.com/2008/crime/08/01/jena6.appeal/index.html 3. people mag gets pitt-jolie pix http://www.cnn.com/2008/showbiz/movies/08/01/brangelina.photos.ap/index.html 4. attack in toronto called racial http://www.cnn.com/2008/world/americas/08/01/canada.attack.ap/index.html 5. ireporters' unusual names http://www.cnn.com/2008/living/08/01/unusual.names.irpt/index.html 6. mother pleads for child's return http://www.cnn.com/2008/crime/08/01/rockefeller.kidnapping/index.html 7. karadzic: i made deal with u.s. http://www.cnn.com/2008/world/europe/08/01/karadzic.trial/index.html 8. suspect arrested in swim killings http://www.cnn.com/2008/crime/08/01/wisconsin.shooting.ap/index.html 9. anthrax suspect apparent suicide http://www.cnn.com/2008/crime/08/01/anthrax.death/index.html 10. mccain: obama criticism 'fair' http://www.cnn.com/2008/politics/08/01/campaign.wrap/index.html cnn, the most trusted name in news> cable news network lp, lllp. <> one cnn center, atlanta, georgia 30303 <> 2008 cable news network lp, lllp. <> a time warner company. <>",1,1,daily top 10,karmandeep-opengevl@universalnet.psi.br,universalnet.psi.br,0,12,19,19,0,0,0,1,3.500000,0.352941,0.647059,1,1,br,564,0.693262,20,5,0,0,0,0.0,3.200000,3.625000,2915,227,145.750000,40,17.621145,0,0.000000,14,11.845815,4.759651,0.735683,1
3,gretchen suggs <externalsep1@loanofficertool.com>,specialpricespharmmoreinfo,welcomefastshippingcustomersupport http://7iwfna.blu.livefilestore.com/y1pxdx3kwzhba8xhxv8tdhbjhn7tj4vt91yqg5lb5-_hs9yudwmu5woteqbo-knuliisb2qjjiug_bnfnrnh0yosw/index.html,1,1,gretchen suggs,externalsep1@loanofficertool.com,loanofficertool.com,0,14,12,19,0,0,1,0,3.106891,0.444444,0.555556,2,1,com,51945,0.655347,26,1,0,0,0,0.0,26.000000,3.584303,171,2,6.576923,1,50.000000,0,0.000000,0,85.000000,5.039773,1.000000,1
4,caroline aragon <dwthaidomainnamesm@thaidomainnames.com>,from caroline aragon,yo wu urs mo ou go rc ebo eform rgi orewo iyv m ww en c mo l cfd ic eym k he uys re,1,0,caroline aragon,dwthaidomainnamesm@thaidomainnames.com,thaidomainnames.com,0,15,18,19,0,0,0,0,3.189898,0.444444,0.555556,1,1,com,51945,0.655347,20,3,0,0,0,0.0,6.000000,3.266333,83,25,4.150000,0,0.000000,0,0.000000,0,2.360000,3.881709,0.960000,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99110,scc <gerry.rossi4360@kinki-kids.com>,job just for you,"while we may have high expectations of our associates, we also give them high rewards. imagine being part of a stable organization with a sterling reputation - a place where the sydney car centre is an integral part of all that we do. with our car centre personality, you'll not just succeed - you'll thrive. and, with our strong commitment to promoting from within, you'll definitely enjoy your rise to the top. today the sydney car centre is looking for an industrious regional assistant to fasten the process of the delivery of customer payments to the suppliers. the position offered is a part-time job, and will only require from you to be available for 1-2 hours a day. as a regional assistant, you will be supposed to operate with the payments from those customers, based in your country. you will be expected to accept 2-3 transactions to your bank account every week, make certain calculations about every transaction (you will be precisely instructed about it), & transfer the funds to the suppliers by means of western union/money gram less your fee & the charges of the western union/money gram. you will be continuously communicating with the manager from the head office, who will instruct you & give advice regarding every new payment. the ideal candidate will be industrious, goal-oriented person, with the availability of a personal/business bank account suitable to be used for the company needs. knowledge of english, computer literacy and sociability are appreciated. the company guarantees to pay net 10% fee out of the amount of every payment you dealt with and to provide you with the regular income & flexible schedule. all the related expenses you might have (like the western union/money gram chargers, related expenses on traveling) are covered by the company. the more detailed information is available on our web-site http://vacancy-85953.centrecar.jp/vacancies.php, where you can fill in the on-line application form for this position. we would be glad to welcome you in our team! we are looking forward to hearing from you as soon as possible! yours sincerely, christian mcgraw 0x58, 0x0, 0x02, 0x44374339, 0x3, 0x21, 0x73, 0x25, 0x40, 0x3025, 0x8736 root type interface start pra engine 0x6, 0x02, 0x0027 ewt: 0x5 0x91, 0x962, 0x2, 0x8, 0x58248114, 0x8725, 0x87, 0x04060476, 0x07601018, 0x617, 0x6, 0x7107 0x801, 0x76, 0x122, 0x54, 0x1439, 0x027, 0x8, 0x9, 0x3851, 0x43171840 0x51, 0x63, 0x581, 0x635, 0x8, 0x2657, 0x835 0x08, 0x35, 0x68335649, 0x0, 0x778, 0x336, 0x023, 0x139, 0x838, 0x19, 0x0, 0x35528531, 0x612, 0x73 0x9 0x48392110, 0x10611482, 0x52, 0x47640628, 0x57, 0x59, 0x07188777 0x737, 0x494, 0x0524 0x4, 0x6061, 0x4, 0x2478, 0x41, 0x302, 0x732, 0x9648, 0x77, 0x46364872, 0x032, 0x5512, 0x4 api 86f oxsm nzk mnw dec. function: 0x3, 0x3, 0x5581, 0x20032567, 0x5128, 0x927, 0x82308357, 0x40034348 0x480, 0x07, 0x5354, 0x4661, 0x99468361, 0x4872, 0x9081 jp9m define define api ltin type: 0x31 0x058, 0x3865, 0x337, 0x1383, 0x1, 0x5, 0x3, 0x9, 0x1, 0x74497178, 0x470 rhkm: 0x8, 0x94, 0x05918949, 0x48, 0x72, 0x42141023, 0x7, 0x777 lzky: 0x1828, 0x6, 0x94, 0x4188, 0x348, 0x7, 0x763, 0x5, 0x007, 0x131, 0x02969321, 0x71 0x1812, 0x078, 0x1197, 0x539, 0x38, 0x2, 0x1243, 0x4 0x4474, 0x4, 0x71902151, 0x3, 0x5010, 0x3718, 0x61, 0x5, 0x279 0x89, 0x42, 0x15, 0x462, 0x4333, 0x44, 0x46164674, 0x26, 0x34 yw7, engine, 1wd, source, serv.0x526, 0x8, 0x57, 0x34, 0x4, 0x82, 0x32, 0x42415739, 0x8572, 0x9352, 0x6624, 0x8, 0x48078041 e02: 0x04, 0x05089855, 0x42777318, 0x0576, 0x5, 0x8627, 0x0925 0x63051887, 0x38, 0x0962, 0x42, 0x41343367, 0x11, 0x29817983, 0x92, 0x89, 0x3340, 0x8, 0x9917, 0x492, 0x6426, 0x050 37tg p7a7 bzv update lehn 1mv u6um 0x7449, 0x907, 0x4144, 0x7367, 0x832, 0x88541945, 0x231, 0x73, 0x06221122, 0x7433",1,1,scc,gerry.rossi4360@kinki-kids.com,kinki-kids.com,0,3,15,14,0,0,4,0,2.370951,0.333333,0.666667,34,0,com,51945,0.655347,16,4,0,0,0,0.0,3.250000,3.026987,3754,578,234.625000,1,0.173010,2,0.053277,0,5.496540,4.918497,0.679931,1
99111,sydney car centre <merrill8783@168city.com>,the reply for your request for a job place,"while we may have high expectations of our associates, we also give them high rewards. imagine being part of a stable organization with a sterling reputation - a place where the sydney car centre is an integral part of all that we do. with our car centre personality, you'll not just succeed - you'll thrive. and, with our strong commitment to promoting from within, you'll definitely enjoy your rise to the top. today the sydney car centre is looking for an industrious regional assistant to fasten the process of the delivery of customer payments to the suppliers. the position offered is a part-time job, and will only require from you to be available for 1-2 hours a day. as a regional assistant, you will be supposed to operate with the payments from those customers, based in your country. you will be expected to accept 2-3 transactions to your bank account every week, make certain calculations about every transaction (you will be precisely instructed about it), & transfer the funds to the suppliers by means of western union/money gram less your fee & the charges of the western union/money gram. you will be continuously communicating with the manager from the head office, who will instruct you & give advice regarding every new payment. the ideal candidate will be industrious, goal-oriented person, with the availability of a personal/business bank account suitable to be used for the company needs. knowledge of english, computer literacy and sociability are appreciated. the company guarantees to pay net 10% fee out of the amount of every payment you dealt with and to provide you with the regular income & flexible schedule. all the related expenses you might have (like the western union/money gram chargers, related expenses on traveling) are covered by the company. the more detailed information is available on our web-site http://vacancy-51148191.scc2007.hk/vacancies.php, where you can fill in the on-line application form for this position. we would be glad to welcome you in our team! we are looking forward to hearing from you as soon as possible! yours sincerely, esmeralda bowman 0x783, 0x06, 0x998, 0x19708859, 0x36004780, 0x56976267, 0x11 lde, zsi, j67, i7uu, yqly, 9f9, yqyz, common. 0hqv: 0x906, 0x182, 0x539, 0x8, 0x13, 0x83, 0x4, 0x153, 0x05, 0x077, 0x62, 0x89098925, 0x5 0x3788, 0x7, 0x07, 0x0617, 0x396, 0x32003361, 0x06, 0x3711, 0x6 fo5: 0x129, 0x75681121, 0x4674, 0x21065124, 0x02 h0an: 0x959, 0x9, 0x3125, 0x88774924, 0x35084569, 0x7822, 0x7, 0x3641, 0x545, 0x2, 0x85, 0x1, 0x52397105, 0x14249123 78z: 0x5, 0x41, 0x08958647, 0x45, 0x48902683, 0x1, 0x79, 0x8, 0x7314, 0x15713459 s6rq: 0x991, 0x09052202, 0x5, 0x78500922, 0x3, 0x8, 0x58, 0x0028, 0x1542 interface: 0x127, 0x6, 0x59099635, 0x42, 0x91085012 0x9236, 0x6446, 0x25, 0x761, 0x4361, 0x8, 0x331, 0x4, 0x4, 0x00324695, 0x4, 0x9103, 0x2, 0x8 0x05, 0x47, 0x1, 0x2, 0x72187495, 0x9, 0x7, 0x4, 0x8, 0x92161701, 0x9100, 0x16089079 0x65624327, 0x26301430, 0x890, 0x478, 0x46401146, 0x66693446, 0x87, 0x44 source stack media 0jn. yi8: 0x14, 0x58142734 0x6837, 0x6826, 0x6846, 0x4, 0x447, 0x4, 0x8, 0x432, 0x015, 0x62, 0x4980 i44 qta5: 0x1855, 0x22 0x29577865, 0x52326092, 0x13 0x6, 0x89, 0x42647350, 0x8031, 0x23164080, 0x998 0x58, 0x2, 0x4095, 0x23511530, 0x697, 0x1 0x85, 0x138, 0x531, 0x0, 0x98777144, 0x276, 0x9508, 0x3, 0x2 tmp: 0x27, 0x74263581, 0x8, 0x0631, 0x8121, 0x7, 0x089, 0x3183 interface: 0x7, 0x49800350, 0x15, 0x881, 0x7557, 0x1386, 0x8796, 0x412, 0x0146 rev api0x43, 0x55541377, 0x5077, 0x31, 0x20, 0x261, 0x43920406, 0x56, 0x92 wzi: 0x4, 0x39, 0x08759946, 0x6, 0x3, 0x11 root: 0x7, 0x49393920, 0x29, 0x3387, 0x7, 0x4, 0x2, 0x18, 0x3, 0x76, 0x1957, 0x394, 0x603 create. stack: 0x63788219, 0x136, 0x2097, 0x698, 0x83030685, 0x86, 0x43407518, 0x5, 0x00, 0x0823, 0x9694, 0x58291764, 0x4",1,1,sydney car centre,merrill8783@168city.com,168city.com,0,17,11,11,1,0,4,0,2.807355,0.285714,0.714286,24,0,com,51945,0.655347,42,9,0,0,0,0.0,3.777778,3.757484,3789,575,90.214286,1,0.173913,2,0.052784,0,5.591304,4.932645,0.666087,1
99112,philippe grosjean <phgrosjean@sciviews.org>,me again about the horrible documentation of tcltk,"for those who are interested, i just cook a little tcltkhelp() functi > >> i think it would help if the tcl/tk manuals were added to the rgui help >> menu. why google when they are >>> ""alberto monteiro"" wrote: >>> >>>> how on earth can i know what are the arguments of any of the functions of >>>> the tcl/tk package? [...] >>> my impression is that you as supposed to look in tck/tk manuals. >>> for example, googling on >>> >>> tk tck getopenfile >>> >>> pointed to this web page: >>> >>> http://www.tcl.tk/man/tcl8.5/tkcmd/getopenfile.htm >>> >>> hope that helps. >>> >> >> mike prager, noaa, beaufort, nc >>> * opinions expressed are personal and not represented otherwise. >>> * any use of tradenames does not constitute a noaa endorsement. >>> >>> >>> r-help@stat.math.ethz .ch mailing list >>> https://stat.ethz.ch/mailman/listinfo/r-help >>> please do read the posting guide >>> http://www.r-project.org/posting-guide.html >>> and provide commented, minimal, self-contained, reproducible code. >>> >>> > > > r-help@stat.math.ethz .ch mailing list > https://stat.ethz.ch/mailman/listinfo/r-help > please do read the posting guide http://www.r-project.org/posting-guide.html > and provide commented, minimal, self-contained, reproducible code. > r-help@stat.math.ethz .ch mailing list https://stat.ethz.ch/mailman/listinfo/r-help please do read the posting guide http://www.r-project.org/posting-guide.html and provide commented, minimal, self-contained, reproducible code.",0,1,philippe grosjean,phgrosjean@sciviews.org,sciviews.org,0,17,10,12,0,0,0,0,2.500000,0.363636,0.636364,8,0,org,11664,0.228995,50,8,0,0,0,0.0,5.375000,3.876749,1480,204,29.600000,11,5.392157,0,0.000000,1,6.259804,4.556244,0.524510,1
99113,bernhard wellhofer <bernhard.wellhoefer@gaia-group.com>,rodbc problem,"hello, as i wrote i call sqlfetch(channel,""t_studie"") and this function generates in the background the concrete query. how can i view/log/... the concrete query? regards, bernhard > > from: duprez cédric [mailto:cedric.duprez@ifn.fr] > sent: friday, july 06, 2007 11:59 am > to: bernhard wellhöfer > cc: r-help@stat.math.ethz .ch > subject: re: [r] rodbc problem > > hello, > > the problem seems to be in the query syntax. > can you show us the query you are trying to perform ? > > regards, > > cedric > > -----message d'origine----- > de : r-help-bounces@stat.math.ethz .ch > [mailto:r-help-bounces@stat.math.ethz.ch] de la part de > bernhard wellhöfer > envoyé : vendredi 6 juillet 2007 11:45 > à : r-help@stat.math.ethz .ch > objet : [r] rodbc problem > > hello, > > i use a rodbc connection to a mysql server on a debian > machine. the call to odbcconnect() seems to be ok, but the > result of the first sqlfetch(channel,""t_studie"") retrieves > this data frame: > > [1] ""[rodbc] error: could not sqlexecdirect"" > [2] ""42000 1064 [mysql][odbc 3.51 > driver][mysqld-5.0.22-debian_1bpo1-log]you have an error in > your sql syntax; check the manual that corresponds to your > mysql server version for the right syntax to use near '\\""t_studi(\\004"" > > please note the funny character at the end of the table name > in the error message. > > the ""test data source"" option on the odbc data source name > configuration panel report success. > > who can help me here? > > regards, > > bernhard > > > > > > > [[alternative html version deleted]] > > > r-help@stat.math.ethz .ch mailing list > https://stat.ethz.ch/mailman/listinfo/r-help > please do read the posting guide > http://www.r-project.org/posting-guide.html > and provide commented, minimal, self-contained, reproducible code. > > > r-help@stat.math.ethz .ch mailing list https://stat.ethz.ch/mailman/listinfo/r-help please do read the posting guide http://www.r-project.org/posting-guide.html and provide commented, minimal, self-contained, reproducible code.",0,1,bernhard wellhofer,bernhard.wellhoefer@gaia-group.com,gaia-group.com,0,18,19,14,0,0,0,0,2.921928,0.500000,0.500000,2,1,com,51945,0.655347,13,2,0,0,0,0.0,6.000000,3.084963,2019,316,155.307692,8,2.531646,0,0.000000,3,5.392405,4.851161,0.490506,1

### DROP UNNECESSARY COLUMNS

In [161]:
print(f"\nDataset shape BEFORE dropping: {email_df.shape}")
print(f"Columns BEFORE: {email_df.columns.tolist()}\n")

# Columns to drop with reasons
columns_to_drop = [
    'sender',           # Raw sender text (acts as unique identifier, causes model to memorize
                        # specific senders instead of learning patterns, creates data leakage
                        # and bias - legitimate senders would always be classified as legitimate)

    'sender_name',      # Extracted sender name (also acts as identifier, model could memorize
                        # specific names like "John Smith" instead of learning structural patterns,
                        # poor generalization to new/unseen names)

    'sender_email',     # Extracted sender email (unique identifier per sender, causes memorization,
                        # model won't generalize to new phishing emails from different addresses,
                        # all useful patterns already captured in engineered features)

    'sender_domain',    # Raw domain text (acts as identifier with 62k+ unique values, causes
                        # memorization of specific domains, replaced by engineered features:
                        # domain_frequency, domain_entropy, domain_length, is_rare_domain, etc.
                        # which capture domain patterns without memorizing specific domains)

    'domain_tld'        # Raw TLD text (categorical with many unique values, already replaced by
                        # numerical features: tld_phishing_ratio and tld_frequency which capture
                        # TLD patterns statistically without needing the raw text)
]

# Drop columns
email_df = email_df.drop(columns=columns_to_drop)

print(f"\nDataset shape AFTER dropping: {email_df.shape}")
print(f"\nColumns AFTER: {email_df.columns.tolist()}")

# Display remaining column categories
print("\n" + "="*80)
print("REMAINING COLUMNS BY CATEGORY")
print("="*80)

# Original columns
original_cols = ['subject', 'body', 'label', 'urls']
print(f"\nOriginal Columns ({len([c for c in original_cols if c in email_df.columns])}):")
print([c for c in original_cols if c in email_df.columns])

# Sender/Domain engineered features
sender_features = [col for col in email_df.columns if col.startswith(('sender_', 'email_', 'domain_', 'is_rare', 'tld_'))]
print(f"\nSender/Domain Engineered Features ({len(sender_features)}):")
print(sender_features)

# Subject engineered features
subject_features = [col for col in email_df.columns if col.startswith('subject_')]
print(f"\nSubject Engineered Features ({len(subject_features)}):")
print(subject_features)

# Body engineered features
body_features = [col for col in email_df.columns if col.startswith('body_')]
print(f"\nBody Engineered Features ({len(body_features)}):")
print(body_features)

print("\n" + "="*80)
print(f"TOTAL COLUMNS: {len(email_df.columns)}")
print(f"TOTAL ENGINEERED FEATURES: {len(sender_features) + len(subject_features) + len(body_features)}")
print("="*80)

Dataset shape BEFORE dropping: (99115, 44)
Columns BEFORE: ['sender', 'subject', 'body', 'label', 'urls', 'sender_name', 'sender_email', 'sender_domain', 'sender_missing', 'sender_name_length', 'email_local_length', 'domain_length', 'domain_has_numbers', 'sender_is_noreply', 'consecutive_digit_length', 'special_char_count', 'domain_entropy', 'domain_vowel_ratio', 'domain_consonant_ratio', 'domain_frequency', 'is_rare_domain', 'domain_tld', 'tld_frequency', 'tld_phishing_ratio', 'subject_length', 'subject_word_count', 'subject_missing', 'subject_exclamation_count', 'subject_question_count', 'subject_special_char_ratio', 'subject_avg_word_length', 'subject_entropy', 'body_length', 'body_word_count', 'body_to_subject_length_ratio', 'body_url_count', 'body_url_density', 'body_exclamation_count', 'body_exclamation_density', 'body_question_count', 'body_avg_word_length', 'body_entropy', 'body_unique_word_ratio', 'body_line_count']


Dataset shape AFTER dropping: (99115, 39)

Columns AFTER: ['subject', 'body', 'label', 'urls', 'sender_missing', 'sender_name_length', 'email_local_length', 'domain_length', 'domain_has_numbers', 'sender_is_noreply', 'consecutive_digit_length', 'special_char_count', 'domain_entropy', 'domain_vowel_ratio', 'domain_consonant_ratio', 'domain_frequency', 'is_rare_domain', 'tld_frequency', 'tld_phishing_ratio', 'subject_length', 'subject_word_count', 'subject_missing', 'subject_exclamation_count', 'subject_question_count', 'subject_special_char_ratio', 'subject_avg_word_length', 'subject_entropy', 'body_length', 'body_word_count', 'body_to_subject_length_ratio', 'body_url_count', 'body_url_density', 'body_exclamation_count', 'body_exclamation_density', 'body_question_count', 'body_avg_word_length', 'body_entropy', 'body_unique_word_ratio', 'body_line_count']

================================================================================
REMAINING COLUMNS BY CATEGORY
================================================================================

Original Columns (4):
['subject', 'body', 'label', 'urls']

Sender/Domain Engineered Features (13):
['sender_missing', 'sender_name_length', 'email_local_length', 'domain_length', 'domain_has_numbers', 'sender_is_noreply', 'domain_entropy', 'domain_vowel_ratio', 'domain_consonant_ratio', 'domain_frequency', 'is_rare_domain', 'tld_frequency', 'tld_phishing_ratio']

Subject Engineered Features (8):
['subject_length', 'subject_word_count', 'subject_missing', 'subject_exclamation_count', 'subject_question_count', 'subject_special_char_ratio', 'subject_avg_word_length', 'subject_entropy']

Body Engineered Features (12):
['body_length', 'body_word_count', 'body_to_subject_length_ratio', 'body_url_count', 'body_url_density', 'body_exclamation_count', 'body_exclamation_density', 'body_question_count', 'body_avg_word_length', 'body_entropy', 'body_unique_word_ratio', 'body_line_count']

================================================================================
TOTAL COLUMNS: 39
TOTAL ENGINEERED FEATURES: 33
================================================================================

## 2. Data Preprocessing

### TEXT CLEANING (After Feature Extraction, Before Vectorization)
#### Cleaning Strategy:
1. Remove URLs (features already extracted: body_url_count, body_url_density)
2. Remove ! and ? (features already extracted: exclamation_count, question_count)
3. Preserve code integrity (code patterns remain intact)
4. Clean excessive whitespace

In [162]:
"""
STEP 1: REMOVE URLs
Reason: URL presence and density already captured in features:
  - body_url_count: actual count of URLs
  - body_url_density: URLs per 100 words
  - urls: boolean flag for URL presence
"""
# Combine all URL patterns into one
combined_url_pattern = '|'.join(url_patterns)

# Count URLs before removal (for verification)
subject_urls_before = email_df['subject'].str.contains(combined_url_pattern, regex=True).sum()
body_urls_before = email_df['body'].str.contains(combined_url_pattern, regex=True).sum()

print(f"\nURLs detected before removal:")
print(f"   Subject: {subject_urls_before} emails contain URLs")
print(f"   Body: {body_urls_before} emails contain URLs")

# Remove URLs from subject and body
email_df['subject'] = email_df['subject'].str.replace(combined_url_pattern, '', regex=True)
email_df['body'] = email_df['body'].str.replace(combined_url_pattern, '', regex=True)

# Verify removal
subject_urls_after = email_df['subject'].str.contains(combined_url_pattern, regex=True).sum()
body_urls_after = email_df['body'].str.contains(combined_url_pattern, regex=True).sum()

print(f"\nURLs detected after removal:")
print(f"   Subject: {subject_urls_after} emails contain URLs")
print(f"   Body: {body_urls_after} emails contain URLs")



"""
STEP 2: REMOVE ! AND ?
Reason: Urgency signals already captured in features:
    - subject_exclamation_count: count of ! in subject
    - subject_question_count: count of ? in subject
    - body_exclamation_count: count of ! in body
    - body_question_count: count of ? in body
    - body_exclamation_density: ! per 100 characters
"""
# Count before removal
subject_punct_before = (email_df['subject'].str.contains(r'[!?]', regex=True)).sum()
body_punct_before = (email_df['body'].str.contains(r'[!?]', regex=True)).sum()

print(f"\nEmails with ! or ? before removal:")
print(f"   Subject: {subject_punct_before} emails")
print(f"   Body: {body_punct_before} emails")

# Remove ! and ? (single or multiple occurrences)
email_df['subject'] = email_df['subject'].str.replace(r'[!?]+', '', regex=True)
email_df['body'] = email_df['body'].str.replace(r'[!?]+', '', regex=True)

# Verify removal
subject_punct_after = (email_df['subject'].str.contains(r'[!?]', regex=True)).sum()
body_punct_after = (email_df['body'].str.contains(r'[!?]', regex=True)).sum()

print(f"\nEmails with ! or ? after removal:")
print(f"   Subject: {subject_punct_after} emails")
print(f"   Body: {body_punct_after} emails")



"""
STEP 3: CLEAN EXCESSIVE WHITESPACE
"""
# Replace multiple spaces with single space and strip
email_df['subject'] = email_df['subject'].str.replace(r'\s+', ' ', regex=True).str.strip()
email_df['body'] = email_df['body'].str.replace(r'\s+', ' ', regex=True).str.strip()

URLs detected before removal:
   Subject: 0 emails contain URLs
   Body: 57514 emails contain URLs

URLs detected after removal:
   Subject: 0 emails contain URLs
   Body: 0 emails contain URLs

Emails with ! or ? before removal:
   Subject: 0 emails
   Body: 56828 emails

Emails with ! or ? after removal:
   Subject: 0 emails
   Body: 0 emails

In [163]:
email_df

,subject,body,label,urls,sender_missing,sender_name_length,email_local_length,domain_length,domain_has_numbers,sender_is_noreply,consecutive_digit_length,special_char_count,domain_entropy,domain_vowel_ratio,domain_consonant_ratio,domain_frequency,is_rare_domain,tld_frequency,tld_phishing_ratio,subject_length,subject_word_count,subject_missing,subject_exclamation_count,subject_question_count,subject_special_char_ratio,subject_avg_word_length,subject_entropy,body_length,body_word_count,body_to_subject_length_ratio,body_url_count,body_url_density,body_exclamation_count,body_exclamation_density,body_question_count,body_avg_word_length,body_entropy,body_unique_word_ratio,body_line_count
0,never agree to be a loser,"buck up, your troubles caused by small dimension will soon be over become a lover no woman will be able to resist come. even as nazi tanks were rolling down the streets, the dreamersphilosopher or a journalist. he was still not sure.i do the same.",1,1,0,14,5,9,0,0,0,0,2.584963,0.375000,0.625000,6,0,3684,0.526873,25,6,0,0,0,0.0,3.333333,3.108695,271,46,10.840000,1,2.173913,2,0.738007,0,4.913043,4.302561,0.891304,1
1,befriend jenna jameson,upgrade your sex and pleasures with these techniques,1,1,0,3,11,9,0,0,4,0,2.584963,0.375000,0.625000,1,1,35,0.914286,22,3,0,0,0,0.0,6.666667,3.321928,78,9,3.545455,2,22.222222,0,0.000000,0,7.777778,4.307525,1.000000,1
2,cnn com daily top 10,"the daily top 10>from cnn.com >top videos and stories as of: aug 1, 2008 3:58 pm edt top 10 videos 1. montauk 'monster' is it a devil dog is it a turtle is it the montauk monster cnn's jeanne moos asks, ""what is this thing"" 2. racy photos of toddler's mom 3. news of the absurd episode 54 4. police beating dispute 5. mom pleads for girl's return 6. defendant fakes heart attack 7. killer carried victim's head 8. murder confession recanted 9. anthrax suspect's home 10. hecklers interrupt obama talk top 10 stories 1. suspect in beheading identified canadian police say vince weiguang li, 40, of edmonton is charged with second-degree murder in the beheading of a man on a bus. 2. judge taken off last jena 6 cases 3. people mag gets pitt-jolie pix 4. attack in toronto called racial 5. ireporters' unusual names 6. mother pleads for child's return 7. karadzic: i made deal with u.s. 8. suspect arrested in swim killings 9. anthrax suspect apparent suicide 10. mccain: obama criticism 'fair' cnn, the most trusted name in news> cable news network lp, lllp. <> one cnn center, atlanta, georgia 30303 <> 2008 cable news network lp, lllp. <> a time warner company. <>",1,1,0,12,19,19,0,0,0,1,3.500000,0.352941,0.647059,1,1,564,0.693262,20,5,0,0,0,0.0,3.200000,3.625000,2915,227,145.750000,40,17.621145,0,0.000000,14,11.845815,4.759651,0.735683,1
3,specialpricespharmmoreinfo,welcomefastshippingcustomersupport,1,1,0,14,12,19,0,0,1,0,3.106891,0.444444,0.555556,2,1,51945,0.655347,26,1,0,0,0,0.0,26.000000,3.584303,171,2,6.576923,1,50.000000,0,0.000000,0,85.000000,5.039773,1.000000,1
4,from caroline aragon,yo wu urs mo ou go rc ebo eform rgi orewo iyv m ww en c mo l cfd ic eym k he uys re,1,0,0,15,18,19,0,0,0,0,3.189898,0.444444,0.555556,1,1,51945,0.655347,20,3,0,0,0,0.0,6.000000,3.266333,83,25,4.150000,0,0.000000,0,0.000000,0,2.360000,3.881709,0.960000,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99110,job just for you,"while we may have high expectations of our associates, we also give them high rewards. imagine being part of a stable organization with a sterling reputation - a place where the sydney car centre is an integral part of all that we do. with our car centre personality, you'll not just succeed - you'll thrive. and, with our strong commitment to promoting from within, you'll definitely enjoy your rise to the top. today the sydney car centre is looking for an industrious regional assistant to fasten the process of the delivery of customer payments to the suppliers. the position offered is a part-time job, and will only require from you to be available for 1-2 hours a day. as a regional assistant, you will be supposed to operate with the payments from those customers, based in your country. you will be expected to accept 2-3 transactions to your bank account every week, make certain calculations about every transaction (you will be precisely instructed about it), & transfer the funds to the suppliers by means of western union/money gram less your fee & the charges of the western union/money gram. you will be continuously communicating with the manager from the head office, who will instruct you & give advice regarding every new payment. the ideal candidate will be industrious, goal-oriented person, with the availability of a personal/business bank account suitable to be used for the company needs. knowledge of english, computer literacy and sociability are appreciated. the company guarantees to pay net 10% fee out of the amount of every payment you dealt with and to provide you with the regular income & flexible schedule. all the related expenses you might have (like the western union/money gram chargers, related expenses on traveling) are covered by the company. the more detailed information is available on our web-site where you can fill in the on-line application form for this position. we would be glad to welcome you in our team we are looking forward to hearing from you as soon as possible yours sincerely, christian mcgraw 0x58, 0x0, 0x02, 0x44374339, 0x3, 0x21, 0x73, 0x25, 0x40, 0x3025, 0x8736 root type interface start pra engine 0x6, 0x02, 0x0027 ewt: 0x5 0x91, 0x962, 0x2, 0x8, 0x58248114, 0x8725, 0x87, 0x04060476, 0x07601018, 0x617, 0x6, 0x7107 0x801, 0x76, 0x122, 0x54, 0x1439, 0x027, 0x8, 0x9, 0x3851, 0x43171840 0x51, 0x63, 0x581, 0x635, 0x8, 0x2657, 0x835 0x08, 0x35, 0x68335649, 0x0, 0x778, 0x336, 0x023, 0x139, 0x838, 0x19, 0x0, 0x35528531, 0x612, 0x73 0x9 0x48392110, 0x10611482, 0x52, 0x47640628, 0x57, 0x59, 0x07188777 0x737, 0x494, 0x0524 0x4, 0x6061, 0x4, 0x2478, 0x41, 0x302, 0x732, 0x9648, 0x77, 0x46364872, 0x032, 0x5512, 0x4 api 86f oxsm nzk mnw dec. function: 0x3, 0x3, 0x5581, 0x20032567, 0x5128, 0x927, 0x82308357, 0x40034348 0x480, 0x07, 0x5354, 0x4661, 0x99468361, 0x4872, 0x9081 jp9m define define api ltin type: 0x31 0x058, 0x3865, 0x337, 0x1383, 0x1, 0x5, 0x3, 0x9, 0x1, 0x74497178, 0x470 rhkm: 0x8, 0x94, 0x05918949, 0x48, 0x72, 0x42141023, 0x7, 0x777 lzky: 0x1828, 0x6, 0x94, 0x4188, 0x348, 0x7, 0x763, 0x5, 0x007, 0x131, 0x02969321, 0x71 0x1812, 0x078, 0x1197, 0x539, 0x38, 0x2, 0x1243, 0x4 0x4474, 0x4, 0x71902151, 0x3, 0x5010, 0x3718, 0x61, 0x5, 0x279 0x89, 0x42, 0x15, 0x462, 0x4333, 0x44, 0x46164674, 0x26, 0x34 yw7, engine, 1wd, source, serv.0x526, 0x8, 0x57, 0x34, 0x4, 0x82, 0x32, 0x42415739, 0x8572, 0x9352, 0x6624, 0x8, 0x48078041 e02: 0x04, 0x05089855, 0x42777318, 0x0576, 0x5, 0x8627, 0x0925 0x63051887, 0x38, 0x0962, 0x42, 0x41343367, 0x11, 0x29817983, 0x92, 0x89, 0x3340, 0x8, 0x9917, 0x492, 0x6426, 0x050 37tg p7a7 bzv update lehn 1mv u6um 0x7449, 0x907, 0x4144, 0x7367, 0x832, 0x88541945, 0x231, 0x73, 0x06221122, 0x7433",1,1,0,3,15,14,0,0,4,0,2.370951,0.333333,0.666667,34,0,51945,0.655347,16,4,0,0,0,0.0,3.250000,3.026987,3754,578,234.625000,1,0.173010,2,0.053277,0,5.496540,4.918497,0.679931,1
99111,the reply for your request for a job place,"while we may have high expectations of our associates, we also give them high rewards. imagine being part of a stable organization with a sterling reputation - a place where the sydney car centre is an integral part of all that we do. with our car centre personality, you'll not just succeed - you'll thrive. and, with our strong commitment to promoting from within, you'll definitely enjoy your rise to the top. today the sydney car centre is looking for an industrious regional assistant to fasten the process of the delivery of customer payments to the suppliers. the position offered is a part-time job, and will only require from you to be available for 1-2 hours a day. as a regional assistant, you will be supposed to operate with the payments from those customers, based in your country. you will be expected to accept 2-3 transactions to your bank account every week, make certain calculations about every transaction (you will be precisely instructed about it), & transfer the funds to the suppliers by means of western union/money gram less your fee & the charges of the western union/money gram. you will be continuously communicating with the manager from the head office, who will instruct you & give advice regarding every new payment. the ideal candidate will be industrious, goal-oriented person, with the availability of a personal/business bank account suitable to be used for the company needs. knowledge of english, computer literacy and sociability are appreciated. the company guarantees to pay net 10% fee out of the amount of every payment you dealt with and to provide you with the regular income & flexible schedule. all the related expenses you might have (like the western union/money gram chargers, related expenses on traveling) are covered by the company. the more detailed information is available on our web-site where you can fill in the on-line application form for this position. we would be glad to welcome you in our team we are looking forward to hearing from you as soon as possible yours sincerely, esmeralda bowman 0x783, 0x06, 0x998, 0x19708859, 0x36004780, 0x56976267, 0x11 lde, zsi, j67, i7uu, yqly, 9f9, yqyz, common. 0hqv: 0x906, 0x182, 0x539, 0x8, 0x13, 0x83, 0x4, 0x153, 0x05, 0x077, 0x62, 0x89098925, 0x5 0x3788, 0x7, 0x07, 0x0617, 0x396, 0x32003361, 0x06, 0x3711, 0x6 fo5: 0x129, 0x75681121, 0x4674, 0x21065124, 0x02 h0an: 0x959, 0x9, 0x3125, 0x88774924, 0x35084569, 0x7822, 0x7, 0x3641, 0x545, 0x2, 0x85, 0x1, 0x52397105, 0x14249123 78z: 0x5, 0x41, 0x08958647, 0x45, 0x48902683, 0x1, 0x79, 0x8, 0x7314, 0x15713459 s6rq: 0x991, 0x09052202, 0x5, 0x78500922, 0x3, 0x8, 0x58, 0x0028, 0x1542 interface: 0x127, 0x6, 0x59099635, 0x42, 0x91085012 0x9236, 0x6446, 0x25, 0x761, 0x4361, 0x8, 0x331, 0x4, 0x4, 0x00324695, 0x4, 0x9103, 0x2, 0x8 0x05, 0x47, 0x1, 0x2, 0x72187495, 0x9, 0x7, 0x4, 0x8, 0x92161701, 0x9100, 0x16089079 0x65624327, 0x26301430, 0x890, 0x478, 0x46401146, 0x66693446, 0x87, 0x44 source stack media 0jn. yi8: 0x14, 0x58142734 0x6837, 0x6826, 0x6846, 0x4, 0x447, 0x4, 0x8, 0x432, 0x015, 0x62, 0x4980 i44 qta5: 0x1855, 0x22 0x29577865, 0x52326092, 0x13 0x6, 0x89, 0x42647350, 0x8031, 0x23164080, 0x998 0x58, 0x2, 0x4095, 0x23511530, 0x697, 0x1 0x85, 0x138, 0x531, 0x0, 0x98777144, 0x276, 0x9508, 0x3, 0x2 tmp: 0x27, 0x74263581, 0x8, 0x0631, 0x8121, 0x7, 0x089, 0x3183 interface: 0x7, 0x49800350, 0x15, 0x881, 0x7557, 0x1386, 0x8796, 0x412, 0x0146 rev api0x43, 0x55541377, 0x5077, 0x31, 0x20, 0x261, 0x43920406, 0x56, 0x92 wzi: 0x4, 0x39, 0x08759946, 0x6, 0x3, 0x11 root: 0x7, 0x49393920, 0x29, 0x3387, 0x7, 0x4, 0x2, 0x18, 0x3, 0x76, 0x1957, 0x394, 0x603 create. stack: 0x63788219, 0x136, 0x2097, 0x698, 0x83030685, 0x86, 0x43407518, 0x5, 0x00, 0x0823, 0x9694, 0x58291764, 0x4",1,1,0,17,11,11,1,0,4,0,2.807355,0.285714,0.714286,24,0,51945,0.655347,42,9,0,0,0,0.0,3.777778,3.757484,3789,575,90.214286,1,0.173913,2,0.052784,0,5.591304,4.932645,0.666087,1
99112,me again about the horrible documentation of tcltk,"for those who are interested, i just cook a little tcltkhelp() functi > >> i think it would help if the tcl/tk manuals were added to the rgui help >> menu. why google when they are >>> ""alberto monteiro"" wrote: >>> >>>> how on earth can i know what are the arguments of any of the functions of >>>> the tcl/tk package [...] >>> my impression is that you as supposed to look in tck/tk manuals. >>> for example, googling on >>> >>> tk tck getopenfile >>> >>> pointed to this web page: >>> >>> >>> >>> hope that helps. >>> >> >> mike prager, noaa, beaufort, nc >>> * opinions expressed are personal and not represented otherwise. >>> * any use of tradenames does not constitute a noaa endorsement. >>> >>> >>> r-help@stat.math.ethz .ch mailing list >>> >>> please do read the posting guide >>> >>> and provide commented, minimal, self-contained, reproducible code. >>> >>> > > > r-help@stat.math.ethz .ch mailing list > > please do read the posting guide > and provide commented, minimal, self-contained, reproducible code. > r-help@stat.math.ethz .ch mailing list please do read the posting guide and provide commented, minimal, self-contained, reproducible code.",0,1,0,17,10,12,0,0,0,0,2.500000,0.363636,0.636364,8,0,11664,0.228995,50,8,0,0,0,0.0,5.375000,3.876749,1480,204,29.600000,11,5.392157,0,0.000000,1,6.259804,4.556244,0.524510,1
99113,rodbc problem,"hello, as i wrote i call sqlfetch(channel,""t_studie"") and this function generates in the background the concrete query. how can i view/log/... the concrete query regards, bernhard > > from: duprez cédric [ > sent: friday, july 06, 2007 11:59 am > to: bernhard wellhöfer > cc: r-help@stat.math.ethz .ch > subject: re: [r] rodbc problem > > hello, > > the problem seems to be in the query syntax. > can you show us the query you are trying to perform > > regards, > > cedric > > -----message d'origine----- > de : r-help-bounces@stat.math.ethz .ch > [ de la part de > bernhard wellhöfer > envoyé : vendredi 6 juillet 2007 11:45 > à : r-help@stat.math.ethz .ch > objet : [r] rodbc problem > > hello, > > i use a rodbc connection to a mysql server on a debian > machine. the call to odbcconnect() seems to be ok, but the > result of the first sqlfetch(channel,""t_studie"") retrieves > this data frame: > > [1] ""[rodbc] error: could not sqlexecdirect"" > [2] ""42000 1064 [mysql][odbc 3.51 > driver][mysqld-5.0.22-debian_1bpo1-log]you have an error in > your sql syntax; check the manual that corresponds to your > mysql server version for the right syntax to use near '\\""t_studi(\\004"" > > please note the funny character at the end of the table name > in the error message. > > the ""test data source"" option on the odbc data source name > configuration panel report success. > > who can help me here > > regards, > > bernhard > > > > > > > [[alternative html version deleted]] > > > r-help@stat.math.ethz .ch mailing list > > please do read the posting guide > > and provide commented, minimal, self-contained, reproducible code. > > > r-help@stat.math.ethz .ch mailing list please do read the posting guide and provide commented, minimal, self-contained, reproducible code.",0,1,0,18,19,14,0,0,0,0,2.921928,0.500000,0.500000,2,1,51945,0.655347,13,2,0,0,0,0.0,6.000000,3.084963,2019,316,155.307692,8,2.531646,0,0.000000,3,5.392405,4.851161,0.490506,1
99114,i wanted the desk at his own laws of the but my orders and what you re no move on,"well, are implicated. when does not the stage where the be seen in minute began. that terminus with some yeahs ago. even if he thundered, hysterically: ends but at starving wages before then plunged into high the spirit. mallow smiled to form an even he blew smoke i can prove to the stars that never learn to his shoulders, his sudden conviction any personal malevolent demon. gorov shrugged his the necessary. do in city council or not seem i couldn't he. ponyets winced at all concerned to the directions to ruin, and for korellian and that seat was now confusion with such as much law: out upon an honorable chamberlain of the first, time would be done my way of the. especially no sir, the empire of the fame empty and weapons the mob: psychology was the symbolism. and selling and of the new emperor, was fitted it to be done shouted wienis life have certainly seems, to be very handy little. we you as though we have to remember him in. there's nothing left the recitation of the heathen is no complete he was pointed out of that he gasped, thinks he had with an afterthought, and so young, there is that, gives us. it now and in numbers. i knew i mean if i'm here, primarily for no green, to his the tip of trader; last father would remind you speaking again. i first on her hair was publis manlio we're receding and see, me: what else; even the main huge, open and his lordship with all the most part of ulterior motive: that he had soured fallen of the psychological moment, of their own a trader came to the deepening snow filled the time ponyets felt obliged: to fool which at least, i see i buy not: the hundred and down so in quite to shoot a pattern: in the odds. by mathematics; which that won't ever seen constructed at a symbolic analysis in politics and toppled to be some day, of the fall of that become liable to innocence: pre nuclear power in that; successfully. i wanted the desk at his own laws: of the. but my orders and what you're no, move on their demands the board then went on its bass way to the indiscwiminate first, year, or the last statement. in the nuclear blaster whose helping hand bribe with cohse, he were locates you ought to recognize that, was to go at random distribution. it's not many planets which for a flurry, and in the empire they'd have had seen trantor. i pass the voice was firm but in the rest in local politics. you're icily (i lack of us). how do so. undoubtedly have believed in the recent successfully for it that he will our duty is for myself. the gold from my deah fellow.",1,0,0,5,7,15,0,0,0,0,2.663533,0.428571,0.571429,2,1,51945,0.655347,81,20,0,0,0,0.0,3.100000,3.973762,2540,473,31.358025,0,0.000000,2,0.078740,3,4.372093,4.307421,0.596195,1

In [164]:
email_df.isnull().sum()

subject                         0
body                            0
label                           0
urls                            0
sender_missing                  0
sender_name_length              0
email_local_length              0
domain_length                   0
domain_has_numbers              0
sender_is_noreply               0
consecutive_digit_length        0
special_char_count              0
domain_entropy                  0
domain_vowel_ratio              0
domain_consonant_ratio          0
domain_frequency                0
is_rare_domain                  0
tld_frequency                   0
tld_phishing_ratio              0
subject_length                  0
subject_word_count              0
subject_missing                 0
subject_exclamation_count       0
subject_question_count          0
subject_special_char_ratio      0
subject_avg_word_length         0
subject_entropy                 0
body_length                     0
body_word_count                 0
body_to_subject_length_ratio    0
body_url_count                  0
body_url_density                0
body_exclamation_count          0
body_exclamation_density        0
body_question_count             0
body_avg_word_length            0
body_entropy                    0
body_unique_word_ratio          0
body_line_count                 0
dtype: int64

#### CHECK AND REMOVE ALL NaN VALUES FROM DATASET

In [165]:
print(f"\nDataset shape BEFORE removing NaNs: {email_df.shape}")

# Check for NaN values in all columns
print("\n1. NaN COUNT PER COLUMN:")
print("-"*80)
nan_summary = email_df.isnull().sum()
print(nan_summary)

total_nans = nan_summary.sum()
print(f"\nTotal NaN values across all columns: {total_nans}")

# Identify columns with NaN values
columns_with_nan = nan_summary[nan_summary > 0].index.tolist()
print(f"\nColumns with NaN values: {columns_with_nan}")

# Show percentage of NaN per column
if len(columns_with_nan) > 0:
    print("\n2. NaN PERCENTAGE PER COLUMN:")
    print("-"*80)
    for col in columns_with_nan:
        nan_pct = (email_df[col].isnull().sum() / len(email_df)) * 100
        print(f"   {col}: {email_df[col].isnull().sum()} NaNs ({nan_pct:.2f}%)")

# Count rows with ANY NaN value
rows_with_nan = email_df.isnull().any(axis=1).sum()
print(f"\n3. ROWS WITH ANY NaN VALUE:")
print("-"*80)
print(f"   Total rows with NaN: {rows_with_nan}")
print(f"   Percentage: {(rows_with_nan / len(email_df)) * 100:.2f}%")

# Show sample of rows with NaN
if rows_with_nan > 0:
    print("\n4. SAMPLE ROWS WITH NaN VALUES:")
    print("-"*80)
    nan_rows = email_df[email_df.isnull().any(axis=1)]
    print(nan_rows.head(10))

    # Check label distribution
    print("\n5. LABEL DISTRIBUTION OF ROWS WITH NaN:")
    print("-"*80)
    print(nan_rows['label'].value_counts())
    print(f"   Phishing: {(nan_rows['label'] == 1).sum()}")
    print(f"   Legitimate: {(nan_rows['label'] == 0).sum()}")

# Drop all rows with ANY NaN values
print("\n6. DROPPING ROWS WITH NaN VALUES...")
print("-"*80)
email_df_clean = email_df.dropna()

print(f"Rows dropped: {len(email_df) - len(email_df_clean)}")
print(f"Dataset shape AFTER removing NaNs: {email_df_clean.shape}")

# Update the main dataframe
email_df = email_df_clean.copy()

# Verify no NaN values remain
print("\n7. VERIFICATION - NaN COUNT AFTER CLEANING:")
print("-"*80)
remaining_nans = email_df.isnull().sum().sum()
print(f"Total remaining NaN values: {remaining_nans}")

Dataset shape BEFORE removing NaNs: (99115, 39)

1. NaN COUNT PER COLUMN:
--------------------------------------------------------------------------------
subject                         0
body                            0
label                           0
urls                            0
sender_missing                  0
sender_name_length              0
email_local_length              0
domain_length                   0
domain_has_numbers              0
sender_is_noreply               0
consecutive_digit_length        0
special_char_count              0
domain_entropy                  0
domain_vowel_ratio              0
domain_consonant_ratio          0
domain_frequency                0
is_rare_domain                  0
tld_frequency                   0
tld_phishing_ratio              0
subject_length                  0
subject_word_count              0
subject_missing                 0
subject_exclamation_count       0
subject_question_count          0
subject_special_char_ratio      0
subject_avg_word_length         0
subject_entropy                 0
body_length                     0
body_word_count                 0
body_to_subject_length_ratio    0
body_url_count                  0
body_url_density                0
body_exclamation_count          0
body_exclamation_density        0
body_question_count             0
body_avg_word_length            0
body_entropy                    0
body_unique_word_ratio          0
body_line_count                 0
dtype: int64

Total NaN values across all columns: 0

Columns with NaN values: []

3. ROWS WITH ANY NaN VALUE:
--------------------------------------------------------------------------------
   Total rows with NaN: 0
   Percentage: 0.00%

6. DROPPING ROWS WITH NaN VALUES...
--------------------------------------------------------------------------------
Rows dropped: 0
Dataset shape AFTER removing NaNs: (99115, 39)

7. VERIFICATION - NaN COUNT AFTER CLEANING:
--------------------------------------------------------------------------------
Total remaining NaN values: 0

#### SUBJECT VECTORIZATION (Unigrams Only)

In [166]:
# Initialize Subject TF-IDF Vectorizer
subject_vectorizer = TfidfVectorizer(
    max_features=2000,      # Keep top 2000 features (subjects are short)
    ngram_range=(1, 1),     # Unigrams only (single words)
    min_df=2,               # Ignore terms appearing in less than 2 documents (noise reduction)
    max_df=0.95,            # Ignore terms appearing in more than 95% of documents (too common)
    sublinear_tf=True       # Use log scaling for term frequency (reduces impact of very frequent terms)
)

# Fit and transform subject text
subject_tfidf = subject_vectorizer.fit_transform(email_df['subject'])

print(f"   Shape: {subject_tfidf.shape}")
print(f"   Features: {subject_tfidf.shape[1]} TF-IDF features (unigrams)")
print(f"   Sparsity: {(1 - subject_tfidf.nnz / (subject_tfidf.shape[0] * subject_tfidf.shape[1])) * 100:.2f}%")

# Sample feature names
print(f"\n   Sample features (first 20):")
print(f"   {subject_vectorizer.get_feature_names_out()[:20]}")

# Convert subject TF-IDF to DataFrame
subject_tfidf_df = pd.DataFrame(
    subject_tfidf.toarray(),
    columns=[f'subject_tfidf_{i}' for i in range(subject_tfidf.shape[1])],
    index=email_df.index  # Preserve original index
)

print(f"Subject TF-IDF DataFrame created: {subject_tfidf_df.shape}")

# Combine with email_df (drop original subject column)
email_df = email_df.drop(columns=['subject'])
email_df = pd.concat([email_df, subject_tfidf_df], axis=1)

print(f"Subject column replaced with TF-IDF features!")
print(f"Updated email_df shape: {email_df.shape}")

   Shape: (99115, 2000)
   Features: 2000 TF-IDF features (unigrams)
   Sparsity: 99.79%

   Sample features (first 20):
   ['00' '000' '01' '02' '03' '04' '05' '0500' '06' '07' '0700' '08' '0800'
 '09' '0em' '0ffers' '0nline' '0rder' '0ver' '10']
Subject TF-IDF DataFrame created: (99115, 2000)
Subject column replaced with TF-IDF features!
Updated email_df shape: (99115, 2038)

#### BODY VECTORIZATION (Unigrams + Bigrams)

##### Initialize Body TF-IDF Vectorizer

##### We use BOTH unigrams and bigrams for body because:

1. Phishing emails use specific PHRASES that indicate malicious intent:
    - "click here", "verify account", "limited time", "act now", "suspended account"
2. Single words (unigrams) alone miss context:
    - "verify" vs "verify account" - the phrase is more suspicious
    - "click" vs "click here" - the phrase is a stronger phishing signal
3. Body text is long enough (~1000 chars avg) to have meaningful bigrams
4. Bigrams capture common phishing patterns that appear as consecutive words
5. The combination gives the model both individual keywords AND contextual phrases

In [167]:

body_vectorizer = TfidfVectorizer(
    max_features=5000,      # Keep top 5000 features (body is longer, needs more features)
    ngram_range=(1, 2),     # Both unigrams (1) and bigrams (2) - captures phrases!
    min_df=2,               # Ignore terms appearing in less than 2 documents
    max_df=0.95,            # Ignore terms appearing in more than 95% of documents
    sublinear_tf=True       # Use log scaling for term frequency
)

# Fit and transform body text
body_tfidf = body_vectorizer.fit_transform(email_df['body'])

print(f"Shape: {body_tfidf.shape}")
print(f"Features: {body_tfidf.shape[1]} TF-IDF features (unigrams + bigrams)")
print(f"Sparsity: {(1 - body_tfidf.nnz / (body_tfidf.shape[0] * body_tfidf.shape[1])) * 100:.2f}%")

# Sample feature names
print(f"\nSample features (first 20):")
sample_features = body_vectorizer.get_feature_names_out()[:20]
print(f"{sample_features}")

# Analyze unigrams vs bigrams
all_features = body_vectorizer.get_feature_names_out()
unigrams = [f for f in all_features if ' ' not in f]
bigrams = [f for f in all_features if ' ' in f]

print(f"\nUnigrams count: {len(unigrams)}")
print(f"Bigrams count: {len(bigrams)}")
print(f"\nSample unigrams (first 10): {unigrams[:10]}")
print(f"Sample bigrams (first 10): {bigrams[:10]}")

# Convert body TF-IDF to DataFrame
print("\nConverting to DataFrame...")
body_tfidf_df = pd.DataFrame(
    body_tfidf.toarray(),
    columns=[f'body_tfidf_{i}' for i in range(body_tfidf.shape[1])],
    index=email_df.index  # Preserve original index
)

print(f"Body TF-IDF DataFrame created: {body_tfidf_df.shape}")

# Combine with email_df (drop original body column)
email_df = email_df.drop(columns=['body'])
email_df = pd.concat([email_df, body_tfidf_df], axis=1)

print(f"Body column replaced with TF-IDF features!")
print(f"Updated email_df shape: {email_df.shape}")

Shape: (99115, 5000)
Features: 5000 TF-IDF features (unigrams + bigrams)
Sparsity: 98.01%

Sample features (first 20):
['00' '00 00' '00 our' '000' '000 00' '000 000' '000 gorillas' '000 loan'
 '0000' '01' '0100' '02' '0200' '03' '04' '0400' '05' '0500' '06' '07']

Unigrams count: 2875
Bigrams count: 2125

Sample unigrams (first 10): ['00', '000', '0000', '01', '0100', '02', '0200', '03', '04', '0400']
Sample bigrams (first 10): ['00 00', '00 our', '000 00', '000 000', '000 gorillas', '000 loan', '09 09', '10 125', '10 bin', '10 edouard']

Converting to DataFrame...
Body TF-IDF DataFrame created: (99115, 5000)
Body column replaced with TF-IDF features!
Updated email_df shape: (99115, 7037)

In [168]:
email_df

       label  urls  sender_missing  sender_name_length  email_local_length  \
0          1     1               0                  14                   5
1          1     1               0                   3                  11
2          1     1               0                  12                  19
3          1     1               0                  14                  12
4          1     0               0                  15                  18
...      ...   ...             ...                 ...                 ...
99110      1     1               0                   3                  15
99111      1     1               0                  17                  11
99112      0     1               0                  17                  10
99113      0     1               0                  18                  19
99114      1     0               0                   5                   7

       domain_length  domain_has_numbers  sender_is_noreply  \
0                  9                   0                  0
1                  9                   0                  0
2                 19                   0                  0
3                 19                   0                  0
4                 19                   0                  0
...              ...                 ...                ...
99110             14                   0                  0
99111             11                   1                  0
99112             12                   0                  0
99113             14                   0                  0
99114             15                   0                  0

       consecutive_digit_length  special_char_count  domain_entropy  \
0                             0                   0        2.584963
1                             4                   0        2.584963
2                             0                   1        3.500000
3                             1                   0        3.106891
4                             0                   0        3.189898
...                         ...                 ...             ...
99110                         4                   0        2.370951
99111                         4                   0        2.807355
99112                         0                   0        2.500000
99113                         0                   0        2.921928
99114                         0                   0        2.663533

       domain_vowel_ratio  domain_consonant_ratio  domain_frequency  \
0                0.375000                0.625000                 6
1                0.375000                0.625000                 1
2                0.352941                0.647059                 1
3                0.444444                0.555556                 2
4                0.444444                0.555556                 1
...                   ...                     ...               ...
99110            0.333333                0.666667                34
99111            0.285714                0.714286                24
99112            0.363636                0.636364                 8
99113            0.500000                0.500000                 2
99114            0.428571                0.571429                 2

       is_rare_domain  tld_frequency  tld_phishing_ratio  subject_length  \
0                   0           3684            0.526873              25
1                   1             35            0.914286              22
2                   1            564            0.693262              20
3                   1          51945            0.655347              26
4                   1          51945            0.655347              20
...               ...            ...                 ...             ...
99110               0          51945            0.655347              16
99111               0          51945            0.655347              42
99112               0          11664            0.228995              50
99113               1          51945            0.655347              13
99114               1          51945            0.655347              81

       subject_word_count  subject_missing  subject_exclamation_count  \
0                       6                0                          0
1                       3                0                          0
2                       5                0                          0
3                       1                0                          0
4                       3                0                          0
...                   ...              ...                        ...
99110                   4                0                          0
99111                   9                0                          0
99112                   8                0                          0
99113                   2                0                          0
99114                  20                0                          0

       subject_question_count  subject_special_char_ratio  \
0                           0                         0.0
1                           0                         0.0
2                           0                         0.0
3                           0                         0.0
4                           0                         0.0
...                       ...                         ...
99110                       0                         0.0
99111                       0                         0.0
99112                       0                         0.0
99113                       0                         0.0
99114                       0                         0.0

       subject_avg_word_length  subject_entropy  body_length  body_word_count  \
0                     3.333333         3.108695          271               46
1                     6.666667         3.321928           78                9
2                     3.200000         3.625000         2915              227
3                    26.000000         3.584303          171                2
4                     6.000000         3.266333           83               25
...                        ...              ...          ...              ...
99110                 3.250000         3.026987         3754              578
99111                 3.777778         3.757484         3789              575
99112                 5.375000         3.876749         1480              204
99113                 6.000000         3.084963         2019              316
99114                 3.100000         3.973762         2540              473

       body_to_subject_length_ratio  body_url_count  body_url_density  \
0                         10.840000               1          2.173913
1                          3.545455               2         22.222222
2                        145.750000              40         17.621145
3                          6.576923               1         50.000000
4                          4.150000               0          0.000000
...                             ...             ...               ...
99110                    234.625000               1          0.173010
99111                     90.214286               1          0.173913
99112                     29.600000              11          5.392157
99113                    155.307692               8          2.531646
99114                     31.358025               0          0.000000

       body_exclamation_count  body_exclamation_density  body_question_count  \
0                           2                  0.738007                    0
1                           0                  0.000000                    0
2                           0                  0.000000                   14
3                           0                  0.000000                    0
4                           0                  0.000000                    0
...                       ...                       ...                  ...
99110                       2                  0.053277                    0
99111                       2                  0.052784                    0
99112                       0                  0.000000                    1
99113                       0                  0.000000                    3
99114                       2                  0.078740                    3

       body_avg_word_length  body_entropy  body_unique_word_ratio  \
0                  4.913043      4.302561                0.891304
1                  7.777778      4.307525                1.000000
2                 11.845815      4.759651                0.735683
3                 85.000000      5.039773                1.000000
4                  2.360000      3.881709                0.960000
...                     ...           ...                     ...
99110              5.496540      4.918497                0.679931
99111              5.591304      4.932645                0.666087
99112              6.259804      4.556244                0.524510
99113              5.392405      4.851161                0.490506
99114              4.372093      4.307421                0.596195

       body_line_count  subject_tfidf_0  subject_tfidf_1  subject_tfidf_2  \
0                    1              0.0              0.0              0.0
1                    1              0.0              0.0              0.0
2                    1              0.0              0.0              0.0
3                    1              0.0              0.0              0.0
4                    1              0.0              0.0              0.0
...                ...              ...              ...              ...
99110                1              0.0              0.0              0.0
99111                1              0.0              0.0              0.0
99112                1              0.0              0.0              0.0
99113                1              0.0              0.0              0.0
99114                1              0.0              0.0              0.0

       subject_tfidf_3  subject_tfidf_4  subject_tfidf_5  subject_tfidf_6  \
0                  0.0              0.0              0.0              0.0
1                  0.0              0.0              0.0              0.0
2                  0.0              0.0              0.0              0.0
3                  0.0              0.0              0.0              0.0
4                  0.0              0.0              0.0              0.0
...                ...              ...              ...              ...
99110              0.0              0.0              0.0              0.0
99111              0.0              0.0              0.0              0.0
99112              0.0              0.0              0.0              0.0
99113              0.0              0.0              0.0              0.0
99114              0.0              0.0              0.0              0.0

       subject_tfidf_7  subject_tfidf_8  subject_tfidf_9  subject_tfidf_10  \
0                  0.0              0.0              0.0               0.0
1                  0.0              0.0              0.0               0.0
2                  0.0              0.0              0.0               0.0
3                  0.0              0.0              0.0               0.0
4                  0.0              0.0              0.0               0.0
...                ...              ...              ...               ...
99110              0.0              0.0              0.0               0.0
99111              0.0              0.0              0.0               0.0
99112              0.0              0.0              0.0               0.0
99113              0.0              0.0              0.0               0.0
99114              0.0              0.0              0.0               0.0

       subject_tfidf_11  subject_tfidf_12  subject_tfidf_13  subject_tfidf_14  \
0                   0.0               0.0               0.0               0.0
1                   0.0               0.0               0.0               0.0
2                   0.0               0.0               0.0               0.0
3                   0.0               0.0               0.0               0.0
4                   0.0               0.0               0.0               0.0
...                 ...               ...               ...               ...
99110               0.0               0.0               0.0               0.0
99111               0.0               0.0               0.0               0.0
99112               0.0               0.0               0.0               0.0
99113               0.0               0.0               0.0               0.0
99114               0.0               0.0               0.0               0.0

       subject_tfidf_15  subject_tfidf_16  subject_tfidf_17  subject_tfidf_18  \
0                   0.0               0.0               0.0               0.0
1                   0.0               0.0               0.0               0.0
2                   0.0               0.0               0.0               0.0
3                   0.0               0.0               0.0               0.0
4                   0.0               0.0               0.0               0.0
...                 ...               ...               ...               ...
99110               0.0               0.0               0.0               0.0
99111               0.0               0.0               0.0               0.0
99112               0.0               0.0               0.0               0.0
99113               0.0               0.0               0.0               0.0
99114               0.0               0.0               0.0               0.0

       subject_tfidf_19  subject_tfidf_20  subject_tfidf_21  subject_tfidf_22  \
0              0.000000               0.0               0.0               0.0
1              0.000000               0.0               0.0               0.0
2              0.456478               0.0               0.0               0.0
3              0.000000               0.0               0.0               0.0
4              0.000000               0.0               0.0               0.0
...                 ...               ...               ...               ...
99110          0.000000               0.0               0.0               0.0
99111          0.000000               0.0               0.0               0.0
99112          0.000000               0.0               0.0               0.0
99113          0.000000               0.0               0.0               0.0
99114          0.000000               0.0               0.0               0.0

       subject_tfidf_23  subject_tfidf_24  subject_tfidf_25  subject_tfidf_26  \
0                   0.0               0.0               0.0               0.0
1                   0.0               0.0               0.0               0.0
2                   0.0               0.0               0.0               0.0
3                   0.0               0.0               0.0               0.0
4                   0.0               0.0               0.0               0.0
...                 ...               ...               ...               ...
99110               0.0               0.0               0.0               0.0
99111               0.0               0.0               0.0               0.0
99112               0.0               0.0               0.0               0.0
99113               0.0               0.0               0.0               0.0
99114               0.0               0.0               0.0               0.0

       subject_tfidf_27  subject_tfidf_28  subject_tfidf_29  subject_tfidf_30  \
0                   0.0               0.0               0.0               0.0
1                   0.0               0.0               0.0               0.0
2                   0.0               0.0               0.0               0.0
3                   0.0               0.0               0.0               0.0
4                   0.0               0.0               0.0               0.0
...                 ...               ...               ...               ...
99110               0.0               0.0               0.0               0.0
99111               0.0               0.0               0.0               0.0
99112               0.0               0.0               0.0               0.0
99113               0.0               0.0               0.0               0.0
99114               0.0               0.0               0.0               0.0

       subject_tfidf_31  subject_tfidf_32  subject_tfidf_33  subject_tfidf_34  \
0                   0.0               0.0               0.0               0.0
1                   0.0               0.0               0.0               0.0
2                   0.0               0.0               0.0               0.0
3                   0.0               0.0               0.0               0.0
4                   0.0               0.0               0.0               0.0
...                 ...               ...               ...               ...
99110               0.0               0.0               0.0               0.0
99111               0.0               0.0               0.0               0.0
99112               0.0               0.0               0.0               0.0
99113               0.0               0.0               0.0               0.0
99114               0.0               0.0               0.0               0.0

       subject_tfidf_35  subject_tfidf_36  subject_tfidf_37  subject_tfidf_38  \
0                   0.0               0.0               0.0               0.0
1                   0.0               0.0               0.0               0.0
2                   0.0               0.0               0.0               0.0
3                   0.0               0.0               0.0               0.0
4                   0.0               0.0               0.0               0.0
...                 ...               ...               ...               ...
99110               0.0               0.0               0.0               0.0
99111               0.0               0.0               0.0               0.0
99112               0.0               0.0               0.0               0.0
99113               0.0               0.0               0.0               0.0
99114               0.0               0.0               0.0               0.0

       subject_tfidf_39  subject_tfidf_40  subject_tfidf_41  subject_tfidf_42  \
0                   0.0               0.0               0.0               0.0
1                   0.0               0.0               0.0               0.0
2                   0.0               0.0               0.0               0.0
3                   0.0               0.0               0.0               0.0
4                   0.0               0.0               0.0               0.0
...                 ...               ...               ...               ...
99110               0.0               0.0               0.0               0.0
99111               0.0               0.0               0.0               0.0
99112               0.0               0.0               0.0               0.0
99113               0.0               0.0               0.0               0.0
99114               0.0               0.0               0.0               0.0

       subject_tfidf_43  subject_tfidf_44  subject_tfidf_45  subject_tfidf_46  \
0                   0.0               0.0               0.0               0.0
1                   0.0               0.0               0.0               0.0
2                   0.0               0.0               0.0               0.0
3                   0.0               0.0               0.0               0.0
4                   0.0               0.0               0.0               0.0
...                 ...               ...               ...               ...